<Type Name="Exception" FullName="System.Exception">
  <Metadata>
    <Meta Name="ms.openlocfilehash" Value="3e876a1482a23c73451498e9a529b706c17f38a0" />
    <Meta Name="ms.sourcegitcommit" Value="f9e3295b6cc303a611a73a84c4b27f9da792ad0d" />
    <Meta Name="ms.translationtype" Value="HT" />
    <Meta Name="ms.contentlocale" Value="it-IT" />
    <Meta Name="ms.lasthandoff" Value="04/26/2018" />
  </Metadata>
  <TypeSignature Language="C#" Value="public class Exception : System.Runtime.InteropServices._Exception, System.Runtime.Serialization.ISerializable" />
  <TypeSignature Language="ILAsm" Value=".class public sequential ansi serializable beforefieldinit Exception extends System.Object implements class System.Runtime.InteropServices._Exception, class System.Runtime.Serialization.ISerializable" />
  <TypeSignature Language="DocId" Value="T:System.Exception" />
  <TypeSignature Language="VB.NET" Value="Public Class Exception&#xA;Implements _Exception, ISerializable" />
  <TypeSignature Language="C++ CLI" Value="public ref class Exception : System::Runtime::InteropServices::_Exception, System::Runtime::Serialization::ISerializable" />
  <AssemblyInfo>
    <AssemblyName>System.Runtime</AssemblyName>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion>4.0.10.0</AssemblyVersion>
    <AssemblyVersion>4.0.20.0</AssemblyVersion>
    <AssemblyVersion>4.1.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.0.0</AssemblyVersion>
    <AssemblyVersion>4.2.1.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <AssemblyInfo>
    <AssemblyName>netstandard</AssemblyName>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Object</BaseTypeName>
  </Base>
  <Interfaces>
    <Interface>
      <InterfaceName>System.Runtime.InteropServices._Exception</InterfaceName>
    </Interface>
    <Interface>
      <InterfaceName>System.Runtime.Serialization.ISerializable</InterfaceName>
    </Interface>
  </Interfaces>
  <Attributes>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)</AttributeName>
    </Attribute>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.ComDefaultInterface(typeof(System.Runtime.InteropServices._Exception))</AttributeName>
    </Attribute>
    <Attribute>
      <AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
    </Attribute>
  </Attributes>
  <Docs>
    <summary>
      <span data-ttu-id="c3de4-101">Rappresenta gli errori che si verificano durante l'esecuzione dell'applicazione.</span>
      <span class="sxs-lookup">
        <span data-stu-id="c3de4-101">Represents errors that occur during application execution.</span>
      </span>
    </summary>
    <remarks>
      <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-102">Questa classe è la classe base per tutte le eccezioni.</span><span class="sxs-lookup"><span data-stu-id="c3de4-102">This class is the base class for all exceptions.</span></span> <span data-ttu-id="c3de4-103">Quando si verifica un errore, il sistema o l'applicazione attualmente in esecuzione segnala generando un'eccezione che contiene informazioni sull'errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-103">When an error occurs, either the system or the currently executing application reports it by throwing an exception that contains information about the error.</span></span> <span data-ttu-id="c3de4-104">Dopo che viene generata un'eccezione, viene gestita dall'applicazione o dal gestore eccezioni predefinito.</span><span class="sxs-lookup"><span data-stu-id="c3de4-104">After an exception is thrown, it is handled by the application or by the default exception handler.</span></span>  
  
 <span data-ttu-id="c3de4-105">Contenuto della sezione:</span><span class="sxs-lookup"><span data-stu-id="c3de4-105">In this section:</span></span>  
  
 <span data-ttu-id="c3de4-106">[Errori ed eccezioni](#Errors) </span><span class="sxs-lookup"><span data-stu-id="c3de4-106">[Errors and exceptions](#Errors) </span></span>  
 <span data-ttu-id="c3de4-107">[Blocchi try/catch](#TryCatch) </span><span class="sxs-lookup"><span data-stu-id="c3de4-107">[Try/catch blocks](#TryCatch) </span></span>  
 <span data-ttu-id="c3de4-108">[Funzionalità di tipo di eccezione](#Features) </span><span class="sxs-lookup"><span data-stu-id="c3de4-108">[Exception type features](#Features) </span></span>  
 <span data-ttu-id="c3de4-109">[Proprietà di classe di eccezione](#Properties) </span><span class="sxs-lookup"><span data-stu-id="c3de4-109">[Exception class properties](#Properties) </span></span>  
 <span data-ttu-id="c3de4-110">[Considerazioni sulle prestazioni](#Performance) </span><span class="sxs-lookup"><span data-stu-id="c3de4-110">[Performance considerations](#Performance) </span></span>  
 <span data-ttu-id="c3de4-111">[Generare nuovamente un'eccezione](#Rethrow) </span><span class="sxs-lookup"><span data-stu-id="c3de4-111">[Re-throwing an exception](#Rethrow) </span></span>  
 <span data-ttu-id="c3de4-112">[Scelta di eccezioni standard](#Standard) </span><span class="sxs-lookup"><span data-stu-id="c3de4-112">[Choosing standard exceptions](#Standard) </span></span>  
 [<span data-ttu-id="c3de4-113">Implementazione di eccezioni personalizzate</span><span class="sxs-lookup"><span data-stu-id="c3de4-113">Implementing custom exceptions</span></span>](#Custom)  
  
<a name="Errors"></a>   
## <a name="errors-and-exceptions"></a><span data-ttu-id="c3de4-114">Errori ed eccezioni</span><span class="sxs-lookup"><span data-stu-id="c3de4-114">Errors and exceptions</span></span>  
 <span data-ttu-id="c3de4-115">Errori di run-time possono verificarsi per diversi motivi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-115">Run-time errors can occur for a variety of reasons.</span></span> <span data-ttu-id="c3de4-116">Tuttavia, non tutti gli errori devono essere gestiti come eccezioni nel codice.</span><span class="sxs-lookup"><span data-stu-id="c3de4-116">However, not all errors should be handled as exceptions in your code.</span></span> <span data-ttu-id="c3de4-117">Ecco alcune categorie di errori che possono verificarsi in fase di esecuzione e il modo appropriato per rispondere ad essi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-117">Here are some categories of errors that can occur at run time and the appropriate ways to respond to them.</span></span>  
  
-   <span data-ttu-id="c3de4-118">**Errori di utilizzo.**</span><span class="sxs-lookup"><span data-stu-id="c3de4-118">**Usage errors.**</span></span> <span data-ttu-id="c3de4-119">Un errore di utilizzo rappresenta un errore nella logica del programma che può generare un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-119">A usage error represents an error in program logic that can result in an exception.</span></span> <span data-ttu-id="c3de4-120">Tuttavia, l'errore deve essere risolti, ma non tramite la gestione delle eccezioni modificando il codice non corretto.</span><span class="sxs-lookup"><span data-stu-id="c3de4-120">However, the error should be addressed not through exception handling but by modifying the faulty code.</span></span> <span data-ttu-id="c3de4-121">Ad esempio, la sostituzione del <xref:System.Object.Equals%28System.Object%29?displayProperty=nameWithType> metodo nell'esempio seguente si presuppone che il `obj` argomento deve essere sempre non null.</span><span class="sxs-lookup"><span data-stu-id="c3de4-121">For example, the override of the <xref:System.Object.Equals%28System.Object%29?displayProperty=nameWithType> method in the following example assumes that the `obj` argument must always be non-null.</span></span>  
  
     [!code-csharp[System.Exception.Class#4](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/usageerrors1.cs#4)]
     [!code-vb[System.Exception.Class#4](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/usageerrors1.vb#4)]  
  
     <span data-ttu-id="c3de4-122">Il <xref:System.NullReferenceException> eccezione generata quando `obj` è `null` può essere eliminato modificando il codice sorgente da testare in modo esplicito i valori null prima di chiamare il <xref:System.Object.Equals%2A?displayProperty=nameWithType> override e quindi ricompilare.</span><span class="sxs-lookup"><span data-stu-id="c3de4-122">The <xref:System.NullReferenceException> exception that results when `obj` is `null` can be eliminated by modifying the source code to explicitly test for null before calling the <xref:System.Object.Equals%2A?displayProperty=nameWithType> override and then re-compiling.</span></span> <span data-ttu-id="c3de4-123">L'esempio seguente contiene il codice di origine corretti che gestisce un `null` argomento.</span><span class="sxs-lookup"><span data-stu-id="c3de4-123">The following example contains the corrected source code that handles a `null` argument.</span></span>  
  
     [!code-csharp[System.Exception.Class#5](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/usageerrors2.cs#5)]
     [!code-vb[System.Exception.Class#5](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/usageerrors2.vb#5)]  
  
     <span data-ttu-id="c3de4-124">Anziché utilizzare eccezioni per gli errori di sintassi, è possibile utilizzare il <xref:System.Diagnostics.Debug.Assert%2A?displayProperty=nameWithType> metodo per identificare gli errori di sintassi nelle build di debug e <xref:System.Diagnostics.Trace.Assert%2A?displayProperty=nameWithType> compila metodo per identificare gli errori di sintassi nel debug e di rilascio.</span><span class="sxs-lookup"><span data-stu-id="c3de4-124">Instead of using exception handling for usage errors, you can use the <xref:System.Diagnostics.Debug.Assert%2A?displayProperty=nameWithType> method to identify usage errors in debug builds, and the <xref:System.Diagnostics.Trace.Assert%2A?displayProperty=nameWithType> method to identify usage errors in both debug and release builds.</span></span> <span data-ttu-id="c3de4-125">Per ulteriori informazioni, vedere [asserzioni nel codice gestito](/visualstudio/debugger/assertions-in-managed-code).</span><span class="sxs-lookup"><span data-stu-id="c3de4-125">For more information, see [Assertions in Managed Code](/visualstudio/debugger/assertions-in-managed-code).</span></span>  
  
-   <span data-ttu-id="c3de4-126">**Errori del programma.**</span><span class="sxs-lookup"><span data-stu-id="c3de4-126">**Program errors.**</span></span> <span data-ttu-id="c3de4-127">Un errore del programma è un errore di runtime che non è possibile evitare necessariamente scrivendo codice privo di errori.</span><span class="sxs-lookup"><span data-stu-id="c3de4-127">A program error is a run-time error that cannot necessarily be avoided by writing bug-free code.</span></span>  
  
     <span data-ttu-id="c3de4-128">In alcuni casi, un errore del programma può riflettere una condizione di errore previsto o routine.</span><span class="sxs-lookup"><span data-stu-id="c3de4-128">In some cases, a program error may reflect an expected or routine error condition.</span></span> <span data-ttu-id="c3de4-129">In questo caso, è consigliabile evitare di utilizzare la gestione delle eccezioni per gestire l'errore di programma e invece di ripetere l'operazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-129">In this case, you may want to avoid using exception handling to deal with the program error and instead retry the operation.</span></span> <span data-ttu-id="c3de4-130">Se l'utente deve essere una data in un determinato formato di input, ad esempio, è possibile analizzare la stringa della data chiamando il <xref:System.DateTime.TryParseExact%2A?displayProperty=nameWithType> metodo, che restituisce un <xref:System.Boolean> valore che indica se l'operazione di analisi ha avuto esito positivo, anziché il <xref:System.DateTime.ParseExact%2A?displayProperty=nameWithType>metodo, che genera un <xref:System.FormatException> eccezione se la stringa della data non può essere convertita in un <xref:System.DateTime> valore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-130">For example, if the user is expected to input a date in a particular format, you can parse the date string by calling the <xref:System.DateTime.TryParseExact%2A?displayProperty=nameWithType> method, which returns a <xref:System.Boolean> value that indicates whether the parse operation succeeded, instead of using the <xref:System.DateTime.ParseExact%2A?displayProperty=nameWithType> method, which throws a <xref:System.FormatException> exception if the date string cannot be converted to a <xref:System.DateTime> value.</span></span> <span data-ttu-id="c3de4-131">Analogamente, se un utente tenta di aprire un file che non esiste, è possibile chiamare innanzitutto il <xref:System.IO.File.Exists%2A?displayProperty=nameWithType> metodo per verificare se il file esiste e, in caso contrario, richiesta all'utente se desidera crearla.</span><span class="sxs-lookup"><span data-stu-id="c3de4-131">Similarly, if a user tries to open a file that does not exist, you can first call the <xref:System.IO.File.Exists%2A?displayProperty=nameWithType> method to check whether the file exists and, if it does not, prompt the user whether he or she wants to create it.</span></span>  
  
     <span data-ttu-id="c3de4-132">In altri casi, un errore del programma riflette una condizione di errore imprevisto che può essere gestita nel codice.</span><span class="sxs-lookup"><span data-stu-id="c3de4-132">In other cases, a program error reflects an unexpected error condition that can be handled in your code.</span></span> <span data-ttu-id="c3de4-133">Ad esempio, anche se è stato eseguito per verificare l'esistenza di un file, potrebbero essere eliminata prima che è possibile aprirla, oppure è danneggiato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-133">For example, even if you've checked to ensure that a file exists, it may be deleted before you can open it, or it may be corrupted.</span></span> <span data-ttu-id="c3de4-134">In tal caso, il tentativo di aprire il file creando un <xref:System.IO.StreamReader> oggetto o la chiamata di <xref:System.IO.File.Open%2A> metodo potrebbe generare un <xref:System.IO.FileNotFoundException> eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-134">In that case, trying to open the file by instantiating a <xref:System.IO.StreamReader> object or calling the <xref:System.IO.File.Open%2A> method may throw a <xref:System.IO.FileNotFoundException> exception.</span></span> <span data-ttu-id="c3de4-135">In questi casi, è necessario utilizzare eccezioni per correggere l'errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-135">In these cases, you should use exception handling to recover from the error.</span></span>  
  
-   <span data-ttu-id="c3de4-136">**Errori di sistema.**</span><span class="sxs-lookup"><span data-stu-id="c3de4-136">**System failures.**</span></span> <span data-ttu-id="c3de4-137">Un errore di sistema è un errore di runtime che non può essere gestito a livello di codice in modo significativo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-137">A system failure is a run-time error that cannot be handled programmatically in a meaningful way.</span></span> <span data-ttu-id="c3de4-138">Ad esempio, è possibile generare qualsiasi metodo un <xref:System.OutOfMemoryException> eccezione se common language runtime non riesce ad allocare memoria aggiuntiva.</span><span class="sxs-lookup"><span data-stu-id="c3de4-138">For example, any method can throw an <xref:System.OutOfMemoryException> exception if the common language runtime is unable to allocate additional memory.</span></span> <span data-ttu-id="c3de4-139">In genere, gli errori di sistema non vengono gestiti tramite la gestione delle eccezioni.</span><span class="sxs-lookup"><span data-stu-id="c3de4-139">Ordinarily, system failures are not handled by using exception handling.</span></span> <span data-ttu-id="c3de4-140">In alternativa, è possibile utilizzare un evento, ad esempio <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> e chiamare il <xref:System.Environment.FailFast%2A?displayProperty=nameWithType> per registrare le informazioni di eccezione e notifica all'utente di errore prima della chiusura dell'applicazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-140">Instead, you may be able to use an event such as <xref:System.AppDomain.UnhandledException?displayProperty=nameWithType> and call the <xref:System.Environment.FailFast%2A?displayProperty=nameWithType> method to log exception information and notify the user of the failure before the application terminates.</span></span>  
  
<a name="TryCatch"></a>   
## <a name="trycatch-blocks"></a><span data-ttu-id="c3de4-141">Blocchi try/catch</span><span class="sxs-lookup"><span data-stu-id="c3de4-141">Try/catch blocks</span></span>  
 <span data-ttu-id="c3de4-142">Common language runtime fornisce un modello di gestione delle eccezioni che si basa sulla rappresentazione delle eccezioni come oggetti e la separazione del codice programma e nella gestione delle eccezioni `try` blocchi e `catch` blocchi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-142">The common language runtime provides an exception handling model that is based on the representation of exceptions as objects, and the separation of program code and exception handling code into `try` blocks and `catch` blocks.</span></span> <span data-ttu-id="c3de4-143">Può essere uno o più `catch` si blocca, ognuna progettata per gestire un particolare tipo di eccezione o un blocco progettato per rilevare un'eccezione più specifica di un altro blocco.</span><span class="sxs-lookup"><span data-stu-id="c3de4-143">There can be one or more `catch` blocks, each designed to handle a particular type of exception, or one block designed to catch a more specific exception than another block.</span></span>  
  
 <span data-ttu-id="c3de4-144">Se un'applicazione gestisce le eccezioni che si verificano durante l'esecuzione di un blocco di codice dell'applicazione, il codice deve essere posizionato all'interno di un `try` istruzione e viene chiamato un `try` blocco.</span><span class="sxs-lookup"><span data-stu-id="c3de4-144">If an application handles exceptions that occur during the execution of a block of application code, the code must be placed within a `try` statement and is called a `try` block.</span></span> <span data-ttu-id="c3de4-145">Il codice dell'applicazione che gestisce le eccezioni generate da un `try` blocco viene inserito all'interno di un `catch` istruzione e viene chiamato un `catch` blocco.</span><span class="sxs-lookup"><span data-stu-id="c3de4-145">Application code that handles exceptions thrown by a `try` block is placed within a `catch` statement and is called a `catch` block.</span></span> <span data-ttu-id="c3de4-146">Zero o più `catch` blocchi sono associati un `try` blocco e ogni `catch` blocco include un tipo di filtro che determina i tipi di eccezioni gestisce.</span><span class="sxs-lookup"><span data-stu-id="c3de4-146">Zero or more `catch` blocks are associated with a `try` block, and each `catch` block includes a type filter that determines the types of exceptions it handles.</span></span>  
  
 <span data-ttu-id="c3de4-147">Quando si verifica un'eccezione un `try` blocco, viene eseguita la ricerca dei `catch` blocchi nell'ordine vengono visualizzati nel codice dell'applicazione, fino a quando non viene individuato un `catch` blocco che gestisce l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-147">When an exception occurs in a `try` block, the system searches the associated `catch` blocks in the order they appear in application code, until it locates a `catch` block that handles the exception.</span></span> <span data-ttu-id="c3de4-148">Oggetto `catch` blocco gestisce un'eccezione di tipo `T` se il filtro del tipo del blocco catch specifica `T` o qualsiasi tipo che `T` deriva da.</span><span class="sxs-lookup"><span data-stu-id="c3de4-148">A `catch` block handles an exception of type `T` if the type filter of the catch block specifies `T` or any type that `T` derives from.</span></span> <span data-ttu-id="c3de4-149">Il sistema si arresta la ricerca dopo il rilevamento del primo `catch` blocco che gestisce l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-149">The system stops searching after it finds the first `catch` block that handles the exception.</span></span> <span data-ttu-id="c3de4-150">Per questo motivo, nel codice dell'applicazione, un `catch` blocco che gestisce un tipo deve essere specificato prima di un `catch` blocco che gestisce i tipi di base, come illustrato nell'esempio riportato di seguito in questa sezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-150">For this reason, in application code, a `catch` block that handles a type must be specified before a `catch` block that handles its base types, as demonstrated in the example that follows this section.</span></span> <span data-ttu-id="c3de4-151">Un blocco catch che gestisce `System.Exception` viene specificato per ultimo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-151">A catch block that handles `System.Exception` is specified last.</span></span>  
  
 <span data-ttu-id="c3de4-152">Se nessuna del `catch` blocchi associati all'oggetto corrente `try` blocco di gestire l'eccezione e l'oggetto `try` blocco è annidato all'interno di altri `try` blocchi nella chiamata corrente, il `catch` blocchi associati alla successiva inclusione `try` blocco vengono cercati.</span><span class="sxs-lookup"><span data-stu-id="c3de4-152">If none of the `catch` blocks associated with the current `try` block handle the exception, and the current `try` block is nested within other `try` blocks in the current call, the `catch` blocks associated with the next enclosing `try` block are searched.</span></span> <span data-ttu-id="c3de4-153">Se non `catch` blocco per l'eccezione viene trovato, il sistema cerca i precedenti livelli di annidamento nella chiamata corrente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-153">If no `catch` block for the exception is found, the system searches previous nesting levels in the current call.</span></span> <span data-ttu-id="c3de4-154">Se non `catch` bloccare per l'eccezione viene trovato nella chiamata corrente, l'eccezione viene passata lo stack di chiamate e stack frame precedente viene cercato un `catch` blocco che gestisce l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-154">If no `catch` block for the exception is found in the current call, the exception is passed up the call stack, and the previous stack frame is searched for a `catch` block that handles the exception.</span></span> <span data-ttu-id="c3de4-155">La ricerca dello stack di chiamate continua fino a quando non viene gestita l'eccezione o fino a quando non esistono alcun altri frame nello stack di chiamate.</span><span class="sxs-lookup"><span data-stu-id="c3de4-155">The search of the call stack continues until the exception is handled or until no more frames exist on the call stack.</span></span> <span data-ttu-id="c3de4-156">Se si raggiunge l'inizio dello stack di chiamate senza ricerca un `catch` viene gestita dal blocco che gestisce l'eccezione, il gestore eccezioni predefinito e la chiusura dell'applicazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-156">If the top of the call stack is reached without finding a `catch` block that handles the exception, the default exception handler handles it and the application terminates.</span></span>  
  
<a name="Features"></a>   
## <a name="exception-type-features"></a><span data-ttu-id="c3de4-157">Funzionalità di tipo di eccezione</span><span class="sxs-lookup"><span data-stu-id="c3de4-157">Exception type features</span></span>  
 <span data-ttu-id="c3de4-158">Tipi di eccezione supportano le funzionalità seguenti:</span><span class="sxs-lookup"><span data-stu-id="c3de4-158">Exception types support the following features:</span></span>  
  
-   <span data-ttu-id="c3de4-159">Testo leggibile che descrive l'errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-159">Human-readable text that describes the error.</span></span> <span data-ttu-id="c3de4-160">Quando si verifica un'eccezione, il runtime crea un messaggio di testo disponibile per informare l'utente la natura dell'errore e per suggerire come risolvere il problema.</span><span class="sxs-lookup"><span data-stu-id="c3de4-160">When an exception occurs, the runtime makes a text message available to inform the user of the nature of the error and to suggest action to resolve the problem.</span></span> <span data-ttu-id="c3de4-161">Questo messaggio di testo viene mantenuto nella <xref:System.Exception.Message%2A> proprietà dell'oggetto eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-161">This text message is held in the <xref:System.Exception.Message%2A> property of the exception object.</span></span> <span data-ttu-id="c3de4-162">Durante la creazione dell'oggetto eccezione, è possibile passare una stringa di testo al costruttore per descrivere i dettagli di tale particolare eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-162">During the creation of the exception object, you can pass a text string to the constructor to describe the details of that particular exception.</span></span> <span data-ttu-id="c3de4-163">Se viene fornito alcun argomento di messaggio di errore al costruttore, viene utilizzato il messaggio di errore predefinito.</span><span class="sxs-lookup"><span data-stu-id="c3de4-163">If no error message argument is supplied to the constructor, the default error message is used.</span></span> <span data-ttu-id="c3de4-164">Per altre informazioni, vedere la proprietà <xref:System.Exception.Message%2A>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-164">For more information, see the <xref:System.Exception.Message%2A> property.</span></span>  
  
-   <span data-ttu-id="c3de4-165">Lo stato dello stack di chiamate quando è stata generata l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-165">The state of the call stack when the exception was thrown.</span></span> <span data-ttu-id="c3de4-166">Il <xref:System.Exception.StackTrace%2A> proprietà riporta una traccia dello stack che può essere usata per determinare se l'errore si verifica nel codice.</span><span class="sxs-lookup"><span data-stu-id="c3de4-166">The <xref:System.Exception.StackTrace%2A> property carries a stack trace that can be used to determine where the error occurs in the code.</span></span> <span data-ttu-id="c3de4-167">La traccia dello stack vengono elencati tutti i metodi chiamati e i numeri di riga nel file di origine in cui vengono effettuate le chiamate.</span><span class="sxs-lookup"><span data-stu-id="c3de4-167">The stack trace lists all the called methods and the line numbers in the source file where the calls are made.</span></span>  
  
<a name="Properties"></a>   
## <a name="exception-class-properties"></a><span data-ttu-id="c3de4-168">Proprietà di classe di eccezione</span><span class="sxs-lookup"><span data-stu-id="c3de4-168">Exception class properties</span></span>  
 <span data-ttu-id="c3de4-169">Il <xref:System.Exception> classe include un numero di proprietà che consentono di identificare la posizione del codice, il tipo, il file della Guida e il motivo dell'eccezione: <xref:System.Exception.StackTrace%2A>, <xref:System.Exception.InnerException%2A>, <xref:System.Exception.Message%2A>, <xref:System.Exception.HelpLink%2A>, <xref:System.Exception.HResult%2A>, <xref:System.Exception.Source%2A>, <xref:System.Exception.TargetSite%2A>, e <xref:System.Exception.Data%2A>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-169">The <xref:System.Exception> class includes a number of properties that help identify the code location, the type, the help file, and the reason for the exception: <xref:System.Exception.StackTrace%2A>, <xref:System.Exception.InnerException%2A>, <xref:System.Exception.Message%2A>, <xref:System.Exception.HelpLink%2A>, <xref:System.Exception.HResult%2A>, <xref:System.Exception.Source%2A>, <xref:System.Exception.TargetSite%2A>, and <xref:System.Exception.Data%2A>.</span></span>  
  
 <span data-ttu-id="c3de4-170">Quando esiste una relazione causale tra due o più eccezioni, il <xref:System.Exception.InnerException%2A> proprietà mantiene queste informazioni.</span><span class="sxs-lookup"><span data-stu-id="c3de4-170">When a causal relationship exists between two or more exceptions, the <xref:System.Exception.InnerException%2A> property maintains this information.</span></span> <span data-ttu-id="c3de4-171">Eccezione esterna generata in risposta all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="c3de4-171">The outer exception is thrown in response to this inner exception.</span></span> <span data-ttu-id="c3de4-172">Il codice che gestisce l'eccezione esterna è possibile utilizzare le informazioni di eccezione interna precedente per gestire l'errore in modo più appropriato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-172">The code that handles the outer exception can use the information from the earlier inner exception to handle the error more appropriately.</span></span> <span data-ttu-id="c3de4-173">Le informazioni aggiuntive sull'eccezione possono essere archiviate come una raccolta di coppie chiave/valore nel <xref:System.Exception.Data%2A> proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-173">Supplementary information about the exception can be stored as a collection of key/value pairs in the <xref:System.Exception.Data%2A> property.</span></span>  
  
 <span data-ttu-id="c3de4-174">La stringa di messaggio di errore che viene passata al costruttore durante la creazione dell'oggetto eccezione deve essere localizzata e può essere fornita da un file di risorse utilizzando la <xref:System.Resources.ResourceManager> classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-174">The error message string that is passed to the constructor during the creation of the exception object should be localized and can be supplied from a resource file by using the <xref:System.Resources.ResourceManager> class.</span></span> <span data-ttu-id="c3de4-175">Per ulteriori informazioni sulle risorse localizzate, vedere il [creazione di assembly Satellite](~/docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md) e [package e distribuzione delle risorse](~/docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md) argomenti.</span><span class="sxs-lookup"><span data-stu-id="c3de4-175">For more information about localized resources, see the [Creating Satellite Assemblies](~/docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md) and [Packaging and Deploying Resources](~/docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md) topics.</span></span>  
  
 <span data-ttu-id="c3de4-176">Per fornire all'utente informazioni dettagliate sulla causa dell'eccezione, il <xref:System.Exception.HelpLink%2A> proprietà può contenere un URL (o URN) in un file della Guida.</span><span class="sxs-lookup"><span data-stu-id="c3de4-176">To provide the user with extensive information about why the exception occurred, the <xref:System.Exception.HelpLink%2A> property can hold a URL (or URN) to a help file.</span></span>  
  
 <span data-ttu-id="c3de4-177">La <xref:System.Exception> classe utilizza HRESULT COR_E_EXCEPTION, con valore 0x80131500.</span><span class="sxs-lookup"><span data-stu-id="c3de4-177">The <xref:System.Exception> class uses the HRESULT COR_E_EXCEPTION, which has the value 0x80131500.</span></span>  
  
 <span data-ttu-id="c3de4-178">Per un elenco di valori di proprietà iniziali per un'istanza di <xref:System.Exception> classe, vedere il <xref:System.Exception.%23ctor%2A> costruttori.</span><span class="sxs-lookup"><span data-stu-id="c3de4-178">For a list of initial property values for an instance of the <xref:System.Exception> class, see the <xref:System.Exception.%23ctor%2A> constructors.</span></span>  
  
<a name="Performance"></a>   
## <a name="performance-considerations"></a><span data-ttu-id="c3de4-179">Considerazioni sulle prestazioni</span><span class="sxs-lookup"><span data-stu-id="c3de4-179">Performance considerations</span></span>  
 <span data-ttu-id="c3de4-180">La generazione o gestione di un'eccezione utilizza una quantità significativa di risorse di sistema e l'ora di esecuzione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-180">Throwing or handling an exception consumes a significant amount of system resources and execution time.</span></span> <span data-ttu-id="c3de4-181">Generare eccezioni solo per gestire le condizioni davvero straordinarie, non per gestire gli eventi stimabili o controllo di flusso.</span><span class="sxs-lookup"><span data-stu-id="c3de4-181">Throw exceptions only to handle truly extraordinary conditions, not to handle predictable events or flow control.</span></span> <span data-ttu-id="c3de4-182">Ad esempio, in alcuni casi, ad esempio quando si sta sviluppando una libreria di classi, è ragionevole generare un'eccezione se un argomento del metodo non è valido, poiché si prevede che il metodo da chiamare con parametri validi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-182">For example, in some cases, such as when you're developing a class library, it's reasonable to throw an exception if a method argument is invalid, because you expect your method to be called with valid parameters.</span></span> <span data-ttu-id="c3de4-183">Un argomento di metodo non valido, in caso contrario il risultato di un errore di utilizzo, significa che si è verificato qualcosa di straordinari.</span><span class="sxs-lookup"><span data-stu-id="c3de4-183">An invalid method argument, if it is not the result of a usage error, means that something extraordinary has occurred.</span></span> <span data-ttu-id="c3de4-184">Al contrario, genera un'eccezione se l'input dell'utente non è valido, poiché è probabile che l'utente potrebbe immettere dati non validi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-184">Conversely, do not throw an exception if user input is invalid, because you can expect users to occasionally enter invalid data.</span></span> <span data-ttu-id="c3de4-185">Invece, forniscono un meccanismo di ripetizione in modo che gli utenti possono immettere input valido.</span><span class="sxs-lookup"><span data-stu-id="c3de4-185">Instead, provide a retry mechanism so users can enter valid input.</span></span> <span data-ttu-id="c3de4-186">Né utilizzare eccezioni per gestire gli errori di sintassi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-186">Nor should you use exceptions to handle usage errors.</span></span> <span data-ttu-id="c3de4-187">Utilizzare invece [asserzioni](/visualstudio/debugger/assertions-in-managed-code) per identificare e correggere gli errori di utilizzo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-187">Instead, use [assertions](/visualstudio/debugger/assertions-in-managed-code) to identify and correct usage errors.</span></span>  
  
 <span data-ttu-id="c3de4-188">Inoltre, non generano un'eccezione quando un codice restituito è sufficiente. non convertire un codice restituito in un'eccezione. e non catch non regolarmente un'eccezione, ignorarla e continuare l'elaborazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-188">In addition, do not throw an exception when a return code is sufficient; do not convert a return code to an exception; and do not routinely catch an exception, ignore it, and then continue processing.</span></span>  
  
<a name="Rethrow"></a>   
## <a name="re-throwing-an-exception"></a><span data-ttu-id="c3de4-189">Nuova generazione di un'eccezione</span><span class="sxs-lookup"><span data-stu-id="c3de4-189">Re-throwing an exception</span></span>  
 <span data-ttu-id="c3de4-190">In molti casi, un gestore di eccezioni richiede semplicemente passare l'eccezione al chiamante.</span><span class="sxs-lookup"><span data-stu-id="c3de4-190">In many cases, an exception handler simply wants to pass the exception on to the caller.</span></span> <span data-ttu-id="c3de4-191">Questa situazione si verifica spesso:</span><span class="sxs-lookup"><span data-stu-id="c3de4-191">This most often occurs in:</span></span>  
  
-   <span data-ttu-id="c3de4-192">Libreria di classi che a sua volta esegue il wrapping di chiamate ai metodi nella libreria di classi .NET Framework o in altre librerie di classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-192">A class library that in turn wraps calls to methods in the .NET Framework class library or other class libraries.</span></span>  
  
-   <span data-ttu-id="c3de4-193">Un'applicazione o una libreria che si verifica un'eccezione irreversibile.</span><span class="sxs-lookup"><span data-stu-id="c3de4-193">An application or library that encounters a fatal exception.</span></span> <span data-ttu-id="c3de4-194">Il gestore di eccezioni è possibile registrare l'eccezione e quindi rigenerare l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-194">The exception handler can log the exception and then re-throw the exception.</span></span>  
  
 <span data-ttu-id="c3de4-195">Il metodo consigliato per generare nuovamente un'eccezione è sufficiente utilizzare il [generare](~/docs/csharp/language-reference/keywords/throw.md) istruzione in c# e [generare](~/docs/visual-basic/language-reference/statements/throw-statement.md) istruzione in Visual Basic senza includere un'espressione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-195">The recommended way to re-throw an exception is to simply use the [throw](~/docs/csharp/language-reference/keywords/throw.md) statement in C# and the [Throw](~/docs/visual-basic/language-reference/statements/throw-statement.md) statement in Visual Basic without including an expression.</span></span> <span data-ttu-id="c3de4-196">In questo modo si garantisce che tutte le informazioni sullo stack di chiamate viene mantenute quando l'eccezione viene propagata al chiamante.</span><span class="sxs-lookup"><span data-stu-id="c3de4-196">This ensures that all call stack information is preserved when the exception is propagated to the caller.</span></span> <span data-ttu-id="c3de4-197">Questa condizione è illustrata nell'esempio seguente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-197">The following example illustrates this.</span></span> <span data-ttu-id="c3de4-198">Un metodo di estensione, stringa `FindOccurrences`, esegue il wrapping di uno o più chiamate a <xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType> senza convalidare gli argomenti in anticipo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-198">A string extension method, `FindOccurrences`, wraps one or more calls to <xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType> without validating its arguments beforehand.</span></span>  
  
 [!code-csharp[System.Exception.Class#6](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow1.cs#6)]
 [!code-vb[System.Exception.Class#6](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow1.vb#6)]  
  
 <span data-ttu-id="c3de4-199">Il chiamante chiama quindi `FindOccurrences` due volte.</span><span class="sxs-lookup"><span data-stu-id="c3de4-199">A caller then calls `FindOccurrences` twice.</span></span> <span data-ttu-id="c3de4-200">Nella seconda chiamata a `FindOccurrences`, passa il chiamante un `null` come stringa di ricerca, i casi il <xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType> metodo consente di generare un <xref:System.ArgumentNullException> eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-200">In the second call to `FindOccurrences`, the caller passes a `null` as the search string, which cases the <xref:System.String.IndexOf%28System.String%2CSystem.Int32%29?displayProperty=nameWithType> method to throw an <xref:System.ArgumentNullException> exception.</span></span> <span data-ttu-id="c3de4-201">Questa eccezione viene gestita mediante il `FindOccurrences` (metodo) e passato al chiamante.</span><span class="sxs-lookup"><span data-stu-id="c3de4-201">This exception is handled by the `FindOccurrences` method and passed back to the caller.</span></span> <span data-ttu-id="c3de4-202">Poiché l'istruzione throw viene usato senza un'espressione, l'output dell'esempio mostra che viene mantenuto lo stack di chiamate.</span><span class="sxs-lookup"><span data-stu-id="c3de4-202">Because the throw statement is used with no expression, the output from the example shows that the call stack is preserved.</span></span>  
  
 [!code-csharp[System.Exception.Class#7](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow1.cs#7)]
 [!code-vb[System.Exception.Class#7](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow1.vb#7)]  
  
 <span data-ttu-id="c3de4-203">Al contrario, se l'eccezione viene generata nuovamente tramite il</span><span class="sxs-lookup"><span data-stu-id="c3de4-203">In contrast, if the exception is re-thrown by using the</span></span>  
  
```csharp  
throw e  
```  
  
```vb  
Throw e  
```  
  
 <span data-ttu-id="c3de4-204">istruzione, lo stack di chiamate completo non viene mantenuto e l'esempio genera il seguente output:</span><span class="sxs-lookup"><span data-stu-id="c3de4-204">statement, the full call stack is not preserved, and the example would generate the following output:</span></span>  
  
```Output  
  
'a' occurs at the following character positions: 4, 7, 15  
  
An exception (ArgumentNullException) occurred.  
Message:  
   Value cannot be null.  
Parameter name: value  
  
Stack Trace:  
      at Library.FindOccurrences(String s, String f)  
   at Example.Main()  
  
```  
  
 <span data-ttu-id="c3de4-205">Un'alternativa leggermente più complessa sia per generare una nuova eccezione, per mantenere informazioni sullo stack di chiamate dell'eccezione originale in un'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="c3de4-205">A slightly more cumbersome alternative is to throw a new exception, and to preserve the original exception's call stack information in an inner exception.</span></span> <span data-ttu-id="c3de4-206">Il chiamante può quindi utilizzare la nuova eccezione <xref:System.Exception.InnerException%2A> proprietà per recuperare il frame dello stack e altre informazioni sull'eccezione originale.</span><span class="sxs-lookup"><span data-stu-id="c3de4-206">The caller can then use the new exception's <xref:System.Exception.InnerException%2A> property to retrieve stack frame and other information about the original exception.</span></span> <span data-ttu-id="c3de4-207">In questo caso, l'istruzione throw è:</span><span class="sxs-lookup"><span data-stu-id="c3de4-207">In this case, the throw statement is:</span></span>  
  
 [!code-csharp[System.Exception.Class#8](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow3.cs#8)]
 [!code-vb[System.Exception.Class#8](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow3.vb#8)]  
  
 <span data-ttu-id="c3de4-208">Il codice utente che gestisce l'eccezione è necessario indicare che il <xref:System.Exception.InnerException%2A> proprietà contiene informazioni riguardanti l'eccezione originale, come illustrato di seguito il gestore dell'eccezione seguente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-208">The user code that handles the exception has to know that the <xref:System.Exception.InnerException%2A> property contains information about the original exception, as the following exception handler illustrates.</span></span>  
  
 [!code-csharp[System.Exception.Class#9](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/rethrow3.cs#9)]
 [!code-vb[System.Exception.Class#9](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/rethrow3.vb#9)]  
  
<a name="Standard"></a>   
## <a name="choosing-standard-exceptions"></a><span data-ttu-id="c3de4-209">Scelta di eccezioni standard</span><span class="sxs-lookup"><span data-stu-id="c3de4-209">Choosing standard exceptions</span></span>  
 <span data-ttu-id="c3de4-210">Quando è necessario generare un'eccezione, è spesso possibile utilizzare un tipo di eccezione esistenti in .NET Framework anziché l'implementazione di un'eccezione personalizzata.</span><span class="sxs-lookup"><span data-stu-id="c3de4-210">When you have to throw an exception, you can often use an existing exception type in the .NET Framework instead of implementing a custom exception.</span></span> <span data-ttu-id="c3de4-211">È consigliabile utilizzare un tipo di eccezione standard in queste due condizioni:</span><span class="sxs-lookup"><span data-stu-id="c3de4-211">You should use a standard exception type under these two conditions:</span></span>  
  
-   <span data-ttu-id="c3de4-212">Si sta generando un'eccezione causata da un errore di utilizzo (ovvero, da un errore nella logica di programma effettuata dallo sviluppatore che chiama il metodo).</span><span class="sxs-lookup"><span data-stu-id="c3de4-212">You are throwing an exception that is caused by a usage error (that is, by an error in program logic made by the developer who is calling your method).</span></span> <span data-ttu-id="c3de4-213">In genere, si genererebbe un'eccezione, ad esempio <xref:System.ArgumentException>, <xref:System.ArgumentNullException>, <xref:System.InvalidOperationException>, o <xref:System.NotSupportedException>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-213">Typically, you would throw an exception such as <xref:System.ArgumentException>, <xref:System.ArgumentNullException>, <xref:System.InvalidOperationException>, or <xref:System.NotSupportedException>.</span></span> <span data-ttu-id="c3de4-214">La stringa fornito al costruttore dell'oggetto eccezione quando creare un'istanza dell'oggetto eccezione deve descrivere l'errore in modo che lo sviluppatore possibile correggere l'errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-214">The string you supply to the exception object's constructor when instantiating the exception object should describe the error so that the developer can fix it.</span></span> <span data-ttu-id="c3de4-215">Per altre informazioni, vedere la proprietà <xref:System.Exception.Message%2A>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-215">For more information, see the <xref:System.Exception.Message%2A> property.</span></span>  
  
-   <span data-ttu-id="c3de4-216">Si sta gestendo un errore che può essere comunicato al chiamante con un'eccezione di .NET Framework esistente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-216">You are handling an error that can be communicated to the caller with an existing .NET Framework exception.</span></span> <span data-ttu-id="c3de4-217">È necessario generare l'eccezione più derivata possibili.</span><span class="sxs-lookup"><span data-stu-id="c3de4-217">You should throw the most derived exception possible.</span></span> <span data-ttu-id="c3de4-218">Ad esempio, se un metodo richiede un argomento sia un membro valido di un tipo di enumerazione, è necessario generare un <xref:System.ComponentModel.InvalidEnumArgumentException> (più derivata) anziché un oggetto <xref:System.ArgumentException>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-218">For example, if a method requires an argument to be a valid member of an enumeration type, you should throw an <xref:System.ComponentModel.InvalidEnumArgumentException> (the most derived class) rather than an <xref:System.ArgumentException>.</span></span>  
  
 <span data-ttu-id="c3de4-219">Nella tabella seguente sono elencati i tipi di eccezioni comuni e le condizioni in cui verrebbe generata.</span><span class="sxs-lookup"><span data-stu-id="c3de4-219">The following table lists common exception types and the conditions under which you would throw them.</span></span>  
  
|<span data-ttu-id="c3de4-220">Eccezione</span><span class="sxs-lookup"><span data-stu-id="c3de4-220">Exception</span></span>|<span data-ttu-id="c3de4-221">Condizione</span><span class="sxs-lookup"><span data-stu-id="c3de4-221">Condition</span></span>|  
|---------------|---------------|  
|<xref:System.ArgumentException>|<span data-ttu-id="c3de4-222">Un argomento non null che viene passato a un metodo non è valido.</span><span class="sxs-lookup"><span data-stu-id="c3de4-222">A non-null argument that is passed to a method is invalid.</span></span>|  
|<xref:System.ArgumentNullException>|<span data-ttu-id="c3de4-223">Un argomento che viene passato a un metodo è `null`.</span><span class="sxs-lookup"><span data-stu-id="c3de4-223">An argument that is passed to a method is `null`.</span></span>|  
|<xref:System.ArgumentOutOfRangeException>|<span data-ttu-id="c3de4-224">Un argomento non rientra nell'intervallo di valori validi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-224">An argument is outside the range of valid values.</span></span>|  
|<xref:System.IO.DirectoryNotFoundException>|<span data-ttu-id="c3de4-225">Parte di un percorso di directory non è valida.</span><span class="sxs-lookup"><span data-stu-id="c3de4-225">Part of a directory path is not valid.</span></span>|  
|<xref:System.DivideByZeroException>|<span data-ttu-id="c3de4-226">Il denominatore in un numero intero o <xref:System.Decimal> operazione di divisione è zero.</span><span class="sxs-lookup"><span data-stu-id="c3de4-226">The denominator in an integer or <xref:System.Decimal> division operation is zero.</span></span>|  
|<xref:System.IO.DriveNotFoundException>|<span data-ttu-id="c3de4-227">Un'unità non è disponibile o non esiste.</span><span class="sxs-lookup"><span data-stu-id="c3de4-227">A drive is unavailable or does not exist.</span></span>|  
|<xref:System.IO.FileNotFoundException>|<span data-ttu-id="c3de4-228">Un file non esiste.</span><span class="sxs-lookup"><span data-stu-id="c3de4-228">A file does not exist.</span></span>|  
|<xref:System.FormatException>|<span data-ttu-id="c3de4-229">Un valore non è presente in un formato appropriato da convertire da una stringa di un metodo di conversione, ad esempio `Parse`.</span><span class="sxs-lookup"><span data-stu-id="c3de4-229">A value is not in an appropriate format to be converted from a string by a conversion method such as `Parse`.</span></span>|  
|<xref:System.IndexOutOfRangeException>|<span data-ttu-id="c3de4-230">Un indice è esterno ai limiti di una matrice o raccolta.</span><span class="sxs-lookup"><span data-stu-id="c3de4-230">An index is outside the bounds of an array or collection.</span></span>|  
|<xref:System.InvalidOperationException>|<span data-ttu-id="c3de4-231">Una chiamata al metodo non è valida nello stato corrente dell'oggetto.</span><span class="sxs-lookup"><span data-stu-id="c3de4-231">A method call is invalid in an object's current state.</span></span>|  
|<xref:System.Collections.Generic.KeyNotFoundException>|<span data-ttu-id="c3de4-232">Impossibile trovare la chiave specificata per l'accesso a un membro in una raccolta.</span><span class="sxs-lookup"><span data-stu-id="c3de4-232">The specified key for accessing a member in a collection cannot be found.</span></span>|  
|<xref:System.NotImplementedException>|<span data-ttu-id="c3de4-233">Un'operazione o metodo non è implementata.</span><span class="sxs-lookup"><span data-stu-id="c3de4-233">A method or operation is not implemented.</span></span>|  
|<xref:System.NotSupportedException>|<span data-ttu-id="c3de4-234">Un'operazione o metodo non è supportata.</span><span class="sxs-lookup"><span data-stu-id="c3de4-234">A method or operation is not supported.</span></span>|  
|<xref:System.ObjectDisposedException>|<span data-ttu-id="c3de4-235">Viene eseguita un'operazione su un oggetto che è stato eliminato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-235">An operation is performed on an object that has been disposed.</span></span>|  
|<xref:System.OverflowException>|<span data-ttu-id="c3de4-236">Un'operazione aritmetica, di cast o conversione produce un overflow.</span><span class="sxs-lookup"><span data-stu-id="c3de4-236">An arithmetic, casting, or conversion operation results in an overflow.</span></span>|  
|<xref:System.IO.PathTooLongException>|<span data-ttu-id="c3de4-237">Un percorso o nome file supera la lunghezza massima definita dal sistema.</span><span class="sxs-lookup"><span data-stu-id="c3de4-237">A path or file name exceeds the maximum system-defined length.</span></span>|  
|<xref:System.PlatformNotSupportedException>|<span data-ttu-id="c3de4-238">L'operazione non è supportata sulla piattaforma corrente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-238">The operation is not supported on the current platform.</span></span>|  
|<xref:System.RankException>|<span data-ttu-id="c3de4-239">A un metodo viene passata una matrice con numero di dimensioni errato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-239">An array with the wrong number of dimensions is passed to a method.</span></span>|  
|<xref:System.TimeoutException>|<span data-ttu-id="c3de4-240">L'intervallo di tempo assegnato a un'operazione è scaduta.</span><span class="sxs-lookup"><span data-stu-id="c3de4-240">The time interval allotted to an operation has expired.</span></span>|  
|<xref:System.UriFormatException>|<span data-ttu-id="c3de4-241">Viene utilizzato un valido identificatore URI (Uniform Resource).</span><span class="sxs-lookup"><span data-stu-id="c3de4-241">An invalid Uniform Resource Identifier (URI) is used.</span></span>|  
  
<a name="Custom"></a>   
## <a name="implementing-custom-exceptions"></a><span data-ttu-id="c3de4-242">Implementazione di eccezioni personalizzate</span><span class="sxs-lookup"><span data-stu-id="c3de4-242">Implementing custom exceptions</span></span>  
 <span data-ttu-id="c3de4-243">Nei seguenti casi, l'utilizzo di un'eccezione di .NET Framework esistente per gestire una condizione di errore non è sufficiente:</span><span class="sxs-lookup"><span data-stu-id="c3de4-243">In the following cases, using an existing .NET Framework exception to handle an error condition is not adequate:</span></span>  
  
-   <span data-ttu-id="c3de4-244">Quando l'eccezione indica un errore del programma univoco che non può essere mappato a un'eccezione di .NET Framework esistente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-244">When the exception reflects a unique program error that cannot be mapped to an existing .NET Framework exception.</span></span>  
  
-   <span data-ttu-id="c3de4-245">Quando l'eccezione richiede gestione, che è diversa da una gestione più appropriata per un'eccezione di .NET Framework esistente o l'eccezione deve essere identificato da un'eccezione analoga.</span><span class="sxs-lookup"><span data-stu-id="c3de4-245">When the exception requires handling that is different from the handling that is appropriate for an existing .NET Framework exception, or the exception must be disambiguated from a similar exception.</span></span> <span data-ttu-id="c3de4-246">Ad esempio, se si genera un <xref:System.ArgumentOutOfRangeException> eccezione durante l'analisi alla rappresentazione numerica di una stringa che è compresa nell'intervallo del tipo integrale di destinazione, è necessario utilizzare la stessa eccezione per un errore generato dal chiamante non è stato specificato il valori vincolati appropriati quando si chiama il metodo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-246">For example, if you throw an <xref:System.ArgumentOutOfRangeException> exception when parsing the numeric representation of a string that is out of range of the target integral type, you would not want to use the same exception for an error that results from the caller not supplying the appropriate constrained values when calling the method.</span></span>  
  
 <span data-ttu-id="c3de4-247">La <xref:System.Exception> classe è la classe di base di tutte le eccezioni in .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="c3de4-247">The <xref:System.Exception> class is the base class of all exceptions in the .NET Framework.</span></span> <span data-ttu-id="c3de4-248">Diverse classi derivate si basano sul comportamento dei membri di ereditato il <xref:System.Exception> classe; non sostituiscono i membri di <xref:System.Exception>, né definiscono i membri univoci.</span><span class="sxs-lookup"><span data-stu-id="c3de4-248">Many derived classes rely on the inherited behavior of the members of the <xref:System.Exception> class; they do not override the members of <xref:System.Exception>, nor do they define any unique members.</span></span>  
  
 <span data-ttu-id="c3de4-249">Per definire la propria classe di eccezione:</span><span class="sxs-lookup"><span data-stu-id="c3de4-249">To define your own exception class:</span></span>  
  
1.  <span data-ttu-id="c3de4-250">Definire una classe che eredita da <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-250">Define a class that inherits from <xref:System.Exception>.</span></span> <span data-ttu-id="c3de4-251">Se necessario, è possibile definire i membri univoci necessari per la classe per fornire informazioni aggiuntive sull'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-251">If necessary, define any unique members needed by your class to provide additional information about the exception.</span></span> <span data-ttu-id="c3de4-252">Ad esempio, il <xref:System.ArgumentException> classe include un <xref:System.ArgumentException.ParamName%2A> proprietà che specifica il nome del parametro il cui argomento che ha causato l'eccezione, e <xref:System.Text.RegularExpressions.RegexMatchTimeoutException> proprietà include un <xref:System.Text.RegularExpressions.RegexMatchTimeoutException.MatchTimeout%2A> proprietà che indica l'intervallo di timeout.</span><span class="sxs-lookup"><span data-stu-id="c3de4-252">For example, the <xref:System.ArgumentException> class includes a <xref:System.ArgumentException.ParamName%2A> property that specifies the name of the parameter whose argument caused the exception, and the <xref:System.Text.RegularExpressions.RegexMatchTimeoutException> property includes a <xref:System.Text.RegularExpressions.RegexMatchTimeoutException.MatchTimeout%2A> property that indicates the time-out interval.</span></span>  
  
2.  <span data-ttu-id="c3de4-253">Se necessario, eseguire l'override di tutti i membri ereditati con funzionalità che si desidera modificare.</span><span class="sxs-lookup"><span data-stu-id="c3de4-253">If necessary, override any inherited members whose functionality you want to change or modify.</span></span> <span data-ttu-id="c3de4-254">Si noti che la maggior parte delle classi derivate esistenti di <xref:System.Exception> non esegue l'override del comportamento di membri ereditati.</span><span class="sxs-lookup"><span data-stu-id="c3de4-254">Note that most existing derived classes of <xref:System.Exception> do not override the behavior of inherited members.</span></span>  
  
3.  <span data-ttu-id="c3de4-255">Determinare se l'oggetto eccezione personalizzata è serializzabile.</span><span class="sxs-lookup"><span data-stu-id="c3de4-255">Determine whether your custom exception object is serializable.</span></span> <span data-ttu-id="c3de4-256">La serializzazione consente di salvare le informazioni sull'eccezione e consente di informazioni sull'eccezione deve essere condiviso da un server e un proxy client in un contesto di comunicazione remota.</span><span class="sxs-lookup"><span data-stu-id="c3de4-256">Serialization enables you to save information about the exception and permits exception information to be shared by a server and a client proxy in a remoting context.</span></span> <span data-ttu-id="c3de4-257">Per rendere l'oggetto eccezione serializzabile, contrassegnarlo con il <xref:System.SerializableAttribute> attributo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-257">To make the exception object serializable, mark it with the <xref:System.SerializableAttribute> attribute.</span></span>  
  
4.  <span data-ttu-id="c3de4-258">Definire i costruttori della classe di eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-258">Define the constructors of your exception class.</span></span> <span data-ttu-id="c3de4-259">In genere, le classi di eccezioni presentano uno o più dei seguenti costruttori:</span><span class="sxs-lookup"><span data-stu-id="c3de4-259">Typically, exception classes have one or more of the following constructors:</span></span>  
  
    -   <span data-ttu-id="c3de4-260"><xref:System.Exception.%23ctor>, che utilizza i valori predefiniti per inizializzare le proprietà di un nuovo oggetto eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-260"><xref:System.Exception.%23ctor>, which uses default values to initialize the properties of a new exception object.</span></span>  
  
    -   <span data-ttu-id="c3de4-261"><xref:System.Exception.%23ctor%28System.String%29>, che inizializza un nuovo oggetto eccezione con un messaggio di errore specificato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-261"><xref:System.Exception.%23ctor%28System.String%29>, which initializes a new exception object with a specified error message.</span></span>  
  
    -   <span data-ttu-id="c3de4-262"><xref:System.Exception.%23ctor%28System.String%2CSystem.Exception%29>, che inizializza un nuovo oggetto eccezione con un'eccezione interna e il messaggio di errore specificato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-262"><xref:System.Exception.%23ctor%28System.String%2CSystem.Exception%29>, which initializes a new exception object with a specified error message and inner exception.</span></span>  
  
    -   <span data-ttu-id="c3de4-263"><xref:System.Exception.%23ctor%28System.Runtime.Serialization.SerializationInfo%2CSystem.Runtime.Serialization.StreamingContext%29>, ovvero un `protected` costruttore che inizializza un nuovo oggetto di eccezione da dati serializzati.</span><span class="sxs-lookup"><span data-stu-id="c3de4-263"><xref:System.Exception.%23ctor%28System.Runtime.Serialization.SerializationInfo%2CSystem.Runtime.Serialization.StreamingContext%29>, which is a `protected` constructor that initializes a new exception object from serialized data.</span></span> <span data-ttu-id="c3de4-264">Se si è scelto di rendere l'oggetto eccezione serializzabile, è necessario implementare questo costruttore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-264">You should implement this constructor if you've chosen to make your exception object serializable.</span></span>  
  
 <span data-ttu-id="c3de4-265">Nell'esempio seguente viene illustrato l'utilizzo di una classe di eccezione personalizzata.</span><span class="sxs-lookup"><span data-stu-id="c3de4-265">The following example illustrates the use of a custom exception class.</span></span> <span data-ttu-id="c3de4-266">Definisce un `NotPrimeException` eccezione generata quando un client tenta di recuperare una sequenza di numeri primi, specificando un numero iniziale non è principale.</span><span class="sxs-lookup"><span data-stu-id="c3de4-266">It defines a `NotPrimeException` exception that is thrown when a client tries to retrieve a sequence of prime numbers by specifying a starting number that is not prime.</span></span> <span data-ttu-id="c3de4-267">L'eccezione definisce una nuova proprietà `NonPrime`, che restituisce il numero di primi-non che ha causato l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-267">The exception defines a new property, `NonPrime`, that returns the non-prime number that caused the exception.</span></span> <span data-ttu-id="c3de4-268">Oltre all'implementazione di un costruttore protetto e un costruttore con <xref:System.Runtime.Serialization.SerializationInfo> e <xref:System.Runtime.Serialization.StreamingContext> parametri per la serializzazione, la `NotPrimeException` classe definisce tre costruttori aggiuntivi per supportare il `NonPrime` proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-268">Besides implementing a protected parameterless constructor and a constructor with <xref:System.Runtime.Serialization.SerializationInfo> and <xref:System.Runtime.Serialization.StreamingContext> parameters for serialization, the `NotPrimeException` class defines three additional constructors to support the `NonPrime` property.</span></span>  <span data-ttu-id="c3de4-269">Ogni costruttore chiama un costruttore di classe di base oltre a mantenere il valore di numeri non primi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-269">Each constructor calls a base class constructor in addition to preserving the value of the non-prime number.</span></span> <span data-ttu-id="c3de4-270">Il `NotPrimeException` classe è contrassegnata anche con il <xref:System.SerializableAttribute> attributo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-270">The `NotPrimeException` class is also marked with the <xref:System.SerializableAttribute> attribute.</span></span>  
  
 [!code-csharp[System.Exception.Class#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/notprimeexception.cs#1)]
 [!code-vb[System.Exception.Class#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/notprimeexception.vb#1)]  
  
 <span data-ttu-id="c3de4-271">La `PrimeNumberGenerator` classe illustrata nell'esempio seguente usa crivello di Eratostene per calcolare la sequenza di numeri primi da 2 a un limite specificato dal client nella chiamata al costruttore della classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-271">The `PrimeNumberGenerator` class shown in the following example uses the Sieve of Eratosthenes to calculate the sequence of prime numbers from 2 to a limit specified by the client in the call to its class constructor.</span></span> <span data-ttu-id="c3de4-272">Il `GetPrimesFrom` metodo restituisce tutti i numeri primi che sono maggiori o uguali al limite inferiore specificato, ma genera un `NotPrimeException` se tale limite inferiore non è un numero primo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-272">The `GetPrimesFrom` method returns all prime numbers that are greater than or equal to a specified lower limit, but throws a `NotPrimeException` if that lower limit is not a prime number.</span></span>  
  
 [!code-csharp[System.Exception.Class#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/primenumbergenerator.cs#2)]
 [!code-vb[System.Exception.Class#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/primenumbergenerator.vb#2)]  
  
 <span data-ttu-id="c3de4-273">Nell'esempio seguente effettua due chiamate al `GetPrimesFrom` (metodo) con i numeri non primi, uno dei quali supera i limiti del dominio applicazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-273">The following example makes two calls to the `GetPrimesFrom` method with non-prime numbers, one of which crosses application domain boundaries.</span></span> <span data-ttu-id="c3de4-274">In entrambi i casi, l'eccezione viene generata e gestita correttamente nel codice client.</span><span class="sxs-lookup"><span data-stu-id="c3de4-274">In both cases, the exception is thrown and successfully handled in client code.</span></span>  
  
 [!code-csharp[System.Exception.Class#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.class/cs/example.cs#3)]
 [!code-vb[System.Exception.Class#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.class/vb/example.vb#3)]  
  
## <a name="windows-runtime-and-includenetv451includesnet-v451-mdmd"></a><span data-ttu-id="c3de4-275">Windows Runtime e [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span><span class="sxs-lookup"><span data-stu-id="c3de4-275">Windows Runtime and [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span></span>  
 <span data-ttu-id="c3de4-276">In [!INCLUDE[net_win8_profile](~/includes/net-win8-profile-md.md)] per [!INCLUDE[win8](~/includes/win8-md.md)], alcune informazioni di eccezione vanno in genere perse quando un'eccezione viene propagata attraverso frame dello stack non .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="c3de4-276">In [!INCLUDE[net_win8_profile](~/includes/net-win8-profile-md.md)] for [!INCLUDE[win8](~/includes/win8-md.md)], some exception information is typically lost when an exception is propagated through non-.NET Framework stack frames.</span></span> <span data-ttu-id="c3de4-277">A partire dal [!INCLUDE[net_v451](~/includes/net-v451-md.md)] e [!INCLUDE[win81](~/includes/win81-md.md)], common language runtime continua a utilizzare originale <xref:System.Exception> oggetto che è stata generata l'eccezione è stato modificato in uno stack frame non .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="c3de4-277">Starting with the [!INCLUDE[net_v451](~/includes/net-v451-md.md)] and [!INCLUDE[win81](~/includes/win81-md.md)], the common language runtime continues to use the original <xref:System.Exception> object that was thrown unless that exception was modified in a non-.NET Framework stack frame.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-278">Nell'esempio seguente viene illustrato un `catch` blocco definito per la gestione <xref:System.ArithmeticException> errori.</span><span class="sxs-lookup"><span data-stu-id="c3de4-278">The following example demonstrates a `catch` block that is defined to handle <xref:System.ArithmeticException> errors.</span></span> <span data-ttu-id="c3de4-279">Questo `catch` anche bloccare le catture <xref:System.DivideByZeroException> errori, poiché <xref:System.DivideByZeroException> deriva da <xref:System.ArithmeticException> ed è presente alcun `catch` blocco definito in modo esplicito per <xref:System.DivideByZeroException> errori.</span><span class="sxs-lookup"><span data-stu-id="c3de4-279">This `catch` block also catches <xref:System.DivideByZeroException> errors, because <xref:System.DivideByZeroException> derives from <xref:System.ArithmeticException> and there is no `catch` block explicitly defined for <xref:System.DivideByZeroException> errors.</span></span>  
  
 [!code-cpp[CatchException#1](~/samples/snippets/cpp/VS_Snippets_CLR/CatchException/CPP/catchexception.cpp#1)]
 [!code-csharp[CatchException#1](~/samples/snippets/csharp/VS_Snippets_CLR/CatchException/CS/catchexception.cs#1)]
 [!code-vb[CatchException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/CatchException/VB/catchexception.vb#1)]  
  
 ]]></format>
    </remarks>
  </Docs>
  <Members>
    <MemberGroup MemberName=".ctor">
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-280">Inizializza una nuova istanza della classe <see cref="T:System.Exception" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-280">Initializes a new instance of the <see cref="T:System.Exception" /> class.</span>
          </span>
        </summary>
      </Docs>
    </MemberGroup>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Exception ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor" />
      <MemberSignature Language="VB.NET" Value="Public Sub New ()" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; Exception();" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-281">Inizializza una nuova istanza della classe <see cref="T:System.Exception" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-281">Initializes a new instance of the <see cref="T:System.Exception" /> class.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-282">Questo costruttore inizializza la proprietà <xref:System.Exception.Message%2A> della nuova istanza in un messaggio  di sistema in cui viene descritto l'errore e che utilizza le impostazioni cultura correnti.</span><span class="sxs-lookup"><span data-stu-id="c3de4-282">This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.</span></span>  
  
 <span data-ttu-id="c3de4-283">Tutte le classi derivate devono fornire il costruttore predefinito.</span><span class="sxs-lookup"><span data-stu-id="c3de4-283">All the derived classes should provide this default constructor.</span></span> <span data-ttu-id="c3de4-284">Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un'istanza di <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-284">The following table shows the initial property values for an instance of <xref:System.Exception>.</span></span>  
  
|<span data-ttu-id="c3de4-285">Proprietà</span><span class="sxs-lookup"><span data-stu-id="c3de4-285">Property</span></span>|<span data-ttu-id="c3de4-286">Valore</span><span class="sxs-lookup"><span data-stu-id="c3de4-286">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="c3de4-287">Riferimento null (`Nothing` in Visual Basic).</span><span class="sxs-lookup"><span data-stu-id="c3de4-287">A null reference (`Nothing` in Visual Basic).</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="c3de4-288">Descrizione localizzata fornita dal sistema.</span><span class="sxs-lookup"><span data-stu-id="c3de4-288">A system-supplied localized description.</span></span>|  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-289">Esempio di codice seguente deriva un `Exception` che utilizza un messaggio predefinito.</span><span class="sxs-lookup"><span data-stu-id="c3de4-289">The following code example derives an `Exception` that uses a predefined message.</span></span> <span data-ttu-id="c3de4-290">Il codice viene illustrato l'utilizzo del costruttore senza parametri per la classe derivata e la base `Exception` classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-290">The code demonstrates the use of the parameterless constructor for the derived class and the base `Exception` class.</span></span>  
  
 [!code-cpp[System.Exception.Ctor#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Ctor/CPP/new.cpp#1)]
 [!code-csharp[System.Exception.Ctor#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Ctor/CS/new.cs#1)]
 [!code-vb[System.Exception.Ctor#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Ctor/VB/new.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Exception (string message);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor(System.String)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; Exception(System::String ^ message);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="c3de4-291">Messaggio in cui viene descritto l'errore.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-291">The message that describes the error.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="c3de4-292">Inizializza una nuova istanza della classe <see cref="T:System.Exception" /> con un messaggio di errore specificato.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-292">Initializes a new instance of the <see cref="T:System.Exception" /> class with a specified error message.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-293">Questo costruttore inizializza la <xref:System.Exception.Message%2A> proprietà della nuova istanza utilizzando il `message` parametro.</span><span class="sxs-lookup"><span data-stu-id="c3de4-293">This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance by using the `message` parameter.</span></span> <span data-ttu-id="c3de4-294">Se il `message` parametro `null`, equivale a chiamare il <xref:System.Exception.%23ctor%2A> costruttore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-294">If the `message` parameter is `null`, this is the same as calling the <xref:System.Exception.%23ctor%2A> constructor.</span></span>  
  
 <span data-ttu-id="c3de4-295">Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un'istanza di <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-295">The following table shows the initial property values for an instance of <xref:System.Exception>.</span></span>  
  
|<span data-ttu-id="c3de4-296">Proprietà</span><span class="sxs-lookup"><span data-stu-id="c3de4-296">Property</span></span>|<span data-ttu-id="c3de4-297">Valore</span><span class="sxs-lookup"><span data-stu-id="c3de4-297">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="c3de4-298">Riferimento null (`Nothing` in Visual Basic).</span><span class="sxs-lookup"><span data-stu-id="c3de4-298">A null reference (`Nothing` in Visual Basic).</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="c3de4-299">Stringa del messaggio di errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-299">The error message string.</span></span>|  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-300">Esempio di codice seguente deriva un `Exception` per una condizione specifica.</span><span class="sxs-lookup"><span data-stu-id="c3de4-300">The following code example derives an `Exception` for a specific condition.</span></span> <span data-ttu-id="c3de4-301">Il codice viene illustrato come utilizzare il costruttore che accetta un messaggio specificato dal chiamante come parametro, per la classe derivata e la base `Exception` classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-301">The code demonstrates the use of the constructor that takes a caller-specified message as a parameter, for both the derived class and the base `Exception` class.</span></span>  
  
 [!code-cpp[System.Exception.Ctor#2](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Ctor/CPP/news.cpp#2)]
 [!code-csharp[System.Exception.Ctor#2](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Ctor/CS/news.cs#2)]
 [!code-vb[System.Exception.Ctor#2](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Ctor/VB/news.vb#2)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="protected Exception (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method familyhidebysig specialname rtspecialname instance void .ctor(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Protected Sub New (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; Exception(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="c3de4-302">Oggetto <see cref="T:System.Runtime.Serialization.SerializationInfo" /> che contiene i dati oggetto serializzati relativi all'eccezione generata.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-302">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="c3de4-303">Oggetto <see cref="T:System.Runtime.Serialization.StreamingContext" /> contenente le informazioni contestuali sull'origine o sulla destinazione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-303">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="c3de4-304">Inizializza una nuova istanza della classe <see cref="T:System.Exception" /> con dati serializzati.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-304">Initializes a new instance of the <see cref="T:System.Exception" /> class with serialized data.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-305">Questo costruttore viene chiamato durante la deserializzazione per ricostituire l'oggetto eccezione trasmesso su un flusso.</span><span class="sxs-lookup"><span data-stu-id="c3de4-305">This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.</span></span> <span data-ttu-id="c3de4-306">Per ulteriori informazioni, vedere [serializzazione XML e SOAP](~/docs/standard/serialization/xml-and-soap-serialization.md).</span><span class="sxs-lookup"><span data-stu-id="c3de4-306">For more information, see [XML and SOAP Serialization](~/docs/standard/serialization/xml-and-soap-serialization.md).</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-307">Esempio di codice seguente definisce una classe serializzabile `Exception` classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-307">The following code example defines a derived serializable `Exception` class.</span></span> <span data-ttu-id="c3de4-308">Il codice impone un errore di divisione-0, quindi crea un'istanza di eccezione derivata mediante il (<xref:System.Runtime.Serialization.SerializationInfo>, <xref:System.Runtime.Serialization.StreamingContext>) costruttore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-308">The code forces a divide-by-0 error and then creates an instance of the derived exception using the (<xref:System.Runtime.Serialization.SerializationInfo>, <xref:System.Runtime.Serialization.StreamingContext>) constructor.</span></span> <span data-ttu-id="c3de4-309">Il codice di serializzazione dell'istanza in un file, il file viene deserializzato in una nuova eccezione, viene generata, quindi rileva e visualizza i dati dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-309">The code serializes the instance to a file, deserializes the file into a new exception, which it throws, and then catches and displays the exception's data.</span></span>  
  
 [!code-cpp[System.Exception.GetObjectData#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CPP/getobjdata.cpp#1)]
 [!code-csharp[System.Exception.GetObjectData#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CS/getobjdata.cs#1)]
 [!code-vb[System.Exception.GetObjectData#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.GetObjectData/VB/getobjdata.vb#1)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentNullException">
          <span data-ttu-id="c3de4-310">Il valore del parametro <paramref name="info" /> è <see langword="null" />.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-310">The <paramref name="info" /> parameter is <see langword="null" />.</span>
          </span>
        </exception>
        <exception cref="T:System.Runtime.Serialization.SerializationException">
          <span data-ttu-id="c3de4-311">Il nome della classe è <see langword="null" /> oppure <see cref="P:System.Exception.HResult" /> è zero (0).</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-311">The class name is <see langword="null" /> or <see cref="P:System.Exception.HResult" /> is zero (0).</span>
          </span>
        </exception>
        <altmember cref="T:System.Runtime.Serialization.SerializationInfo" />
        <altmember cref="T:System.Runtime.Serialization.StreamingContext" />
      </Docs>
    </Member>
    <Member MemberName=".ctor">
      <MemberSignature Language="C#" Value="public Exception (string message, Exception innerException);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname rtspecialname instance void .ctor(string message, class System.Exception innerException) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.#ctor(System.String,System.Exception)" />
      <MemberSignature Language="VB.NET" Value="Public Sub New (message As String, innerException As Exception)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; Exception(System::String ^ message, Exception ^ innerException);" />
      <MemberType>Constructor</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Parameters>
        <Parameter Name="message" Type="System.String" />
        <Parameter Name="innerException" Type="System.Exception" />
      </Parameters>
      <Docs>
        <param name="message">
          <span data-ttu-id="c3de4-312">Messaggio di errore in cui viene indicato il motivo dell'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-312">The error message that explains the reason for the exception.</span>
          </span>
        </param>
        <param name="innerException">
          <span data-ttu-id="c3de4-313">Eccezione causa dell'eccezione corrente o riferimento Null (<see langword="Nothing" /> in Visual Basic) se non viene specificata alcuna eccezione interna.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-313">The exception that is the cause of the current exception, or a null reference (<see langword="Nothing" /> in Visual Basic) if no inner exception is specified.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="c3de4-314">Inizializza una nuova istanza della classe <see cref="T:System.Exception" /> con un messaggio di errore specificato e un riferimento all'eccezione interna che è la causa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-314">Initializes a new instance of the <see cref="T:System.Exception" /> class with a specified error message and a reference to the inner exception that is the cause of this exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-315">Un'eccezione generata come risultato diretto di un'eccezione precedente deve includere un riferimento all'eccezione precedente nella proprietà <xref:System.Exception.InnerException%2A>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-315">An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property.</span></span> <span data-ttu-id="c3de4-316">La proprietà <xref:System.Exception.InnerException%2A> restituisce lo stesso valore che viene passato al costruttore o un riferimento null (`Nothing` in Visual Basic), se la proprietà <xref:System.Exception.InnerException%2A> non fornisce al costruttore il valore dell'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="c3de4-316">The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.</span></span>  
  
 <span data-ttu-id="c3de4-317">Nella tabella seguente vengono illustrati i valori di proprietà iniziali per un'istanza di <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-317">The following table shows the initial property values for an instance of <xref:System.Exception>.</span></span>  
  
|<span data-ttu-id="c3de4-318">Proprietà</span><span class="sxs-lookup"><span data-stu-id="c3de4-318">Property</span></span>|<span data-ttu-id="c3de4-319">Valore</span><span class="sxs-lookup"><span data-stu-id="c3de4-319">Value</span></span>|  
|--------------|-----------|  
|<xref:System.Exception.InnerException%2A>|<span data-ttu-id="c3de4-320">Riferimento all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="c3de4-320">The inner exception reference.</span></span>|  
|<xref:System.Exception.Message%2A>|<span data-ttu-id="c3de4-321">Stringa del messaggio di errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-321">The error message string.</span></span>|  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-322">Esempio di codice seguente deriva un `Exception` per una condizione specifica.</span><span class="sxs-lookup"><span data-stu-id="c3de4-322">The following code example derives an `Exception` for a specific condition.</span></span> <span data-ttu-id="c3de4-323">Il codice viene illustrato come utilizzare il costruttore che accetta un messaggio e l'eccezione interna come parametri, per la classe derivata e la base `Exception` classe.</span><span class="sxs-lookup"><span data-stu-id="c3de4-323">The code demonstrates the use of the constructor that takes a message and an inner exception as parameters, for both the derived class and the base `Exception` class.</span></span>  
  
 [!code-cpp[System.Exception.Ctor#3](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Ctor/CPP/newsi.cpp#3)]
 [!code-csharp[System.Exception.Ctor#3](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Ctor/CS/newsi.cs#3)]
 [!code-vb[System.Exception.Ctor#3](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Ctor/VB/newsi.vb#3)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Data">
      <MemberSignature Language="C#" Value="public virtual System.Collections.IDictionary Data { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Collections.IDictionary Data" />
      <MemberSignature Language="DocId" Value="P:System.Exception.Data" />
      <MemberSignature Language="VB.NET" Value="Public Overridable ReadOnly Property Data As IDictionary" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::Collections::IDictionary ^ Data { System::Collections::IDictionary ^ get(); };" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Collections.IDictionary</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-324">Ottiene una raccolta di coppie chiave-valore che fornisce informazioni aggiuntive definite dall'utente relative all'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-324">Gets a collection of key/value pairs that provide additional user-defined information about the exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-325">Oggetto che implementa l'interfaccia <see cref="T:System.Collections.IDictionary" /> e contiene una raccolta di coppie chiave/valore definite dall'utente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-325">An object that implements the <see cref="T:System.Collections.IDictionary" /> interface and contains a collection of user-defined key/value pairs.</span>
          </span>
          <span data-ttu-id="c3de4-326">Il valore predefinito è una raccolta vuota.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-326">The default is an empty collection.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-327">Utilizzare il <xref:System.Collections.IDictionary?displayProperty=nameWithType> oggetto restituito dal <xref:System.Exception.Data%2A> proprietà per archiviare e recuperare informazioni supplementari relative all'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-327">Use the <xref:System.Collections.IDictionary?displayProperty=nameWithType> object returned by the <xref:System.Exception.Data%2A> property to store and retrieve supplementary information relevant to the exception.</span></span> <span data-ttu-id="c3de4-328">Le informazioni sono sotto forma di un numero arbitrario di coppie chiave/valore definite dall'utente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-328">The information is in the form of an arbitrary number of user-defined key/value pairs.</span></span> <span data-ttu-id="c3de4-329">Il componente chiave di ogni coppia chiave/valore in genere è una stringa di identificazione, mentre il componente valore della coppia può essere qualsiasi tipo di oggetto.</span><span class="sxs-lookup"><span data-stu-id="c3de4-329">The key component of each key/value pair is typically an identifying string, whereas the value component of the pair can be any type of object.</span></span>  
  
## <a name="keyvalue-pair-security"></a><span data-ttu-id="c3de4-330">Sicurezza della coppia chiave/valore</span><span class="sxs-lookup"><span data-stu-id="c3de4-330">Key/Value Pair Security</span></span>  
 <span data-ttu-id="c3de4-331">Le coppie chiave/valore archiviate nella raccolta restituita dal <xref:System.Exception.Data%2A> proprietà non sono protette.</span><span class="sxs-lookup"><span data-stu-id="c3de4-331">The key/value pairs stored in the collection returned by the <xref:System.Exception.Data%2A> property are not secure.</span></span> <span data-ttu-id="c3de4-332">Se l'applicazione chiama una serie nidificata di routine e ogni routine contiene gestori di eccezioni, lo stack di chiamate risultante contiene una gerarchia di tali gestori di eccezioni.</span><span class="sxs-lookup"><span data-stu-id="c3de4-332">If your application calls a nested series of routines, and each routine contains exception handlers, the resulting call stack contains a hierarchy of those exception handlers.</span></span> <span data-ttu-id="c3de4-333">Se una routine di basso livello genera un'eccezione, un gestore di eccezioni di livello superiore nella gerarchia di stack di chiamate può leggere e/o modificare le coppie chiave/valore archiviate nella raccolta da un altro gestore di eccezioni.</span><span class="sxs-lookup"><span data-stu-id="c3de4-333">If a lower-level routine throws an exception, any upper-level exception handler in the call stack hierarchy can read and/or modify the key/value pairs stored in the collection by any other exception handler.</span></span> <span data-ttu-id="c3de4-334">Ciò significa che è necessario garantire che le informazioni nelle coppie chiave/valore non sono riservate e che l'applicazione funzionerà correttamente se le informazioni nelle coppie chiave/valore sono danneggiate.</span><span class="sxs-lookup"><span data-stu-id="c3de4-334">This means you must guarantee that the information in the key/value pairs is not confidential and that your application will operate correctly if the information in the key/value pairs is corrupted.</span></span>  
  
## <a name="key-conflicts"></a><span data-ttu-id="c3de4-335">Conflitti di chiave</span><span class="sxs-lookup"><span data-stu-id="c3de4-335">Key Conflicts</span></span>  
 <span data-ttu-id="c3de4-336">Quando i gestori di eccezioni diversi specificano la stessa chiave per accedere a una coppia chiave/valore, si verifica un conflitto di chiave.</span><span class="sxs-lookup"><span data-stu-id="c3de4-336">A key conflict occurs when different exception handlers specify the same key to access a key/value pair.</span></span> <span data-ttu-id="c3de4-337">Prestare attenzione quando si sviluppa l'applicazione perché la conseguenza di un conflitto di chiave è che i gestori di eccezioni di livello inferiore possono comunicare inavvertitamente con gestori di eccezioni di livello superiore e la comunicazione potrebbe causare errori insidiosi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-337">Use caution when developing your application because the consequence of a key conflict is that lower-level exception handlers can inadvertently communicate with higher-level exception handlers, and this communication might cause subtle program errors.</span></span> <span data-ttu-id="c3de4-338">Tuttavia, se si è necessario prestare attenzione è possibile utilizzare i conflitti di chiave per migliorare l'applicazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-338">However, if you are cautious you can use key conflicts to enhance your application.</span></span>  
  
## <a name="avoiding-key-conflicts"></a><span data-ttu-id="c3de4-339">Evitare i conflitti di chiave</span><span class="sxs-lookup"><span data-stu-id="c3de4-339">Avoiding Key Conflicts</span></span>  
 <span data-ttu-id="c3de4-340">Evitare i conflitti di chiave adottando una convenzione di denominazione per generare le chiavi univoche per le coppie chiave/valore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-340">Avoid key conflicts by adopting a naming convention to generate unique keys for key/value pairs.</span></span> <span data-ttu-id="c3de4-341">Ad esempio, una convenzione di denominazione potrebbe generare una chiave che è costituito dal nome delimitato da punto dell'applicazione, il metodo che fornisce informazioni supplementari per la coppia e un identificatore univoco.</span><span class="sxs-lookup"><span data-stu-id="c3de4-341">For example, a naming convention might yield a key that consists of the period-delimited name of your application, the method that provides supplementary information for the pair, and a unique identifier.</span></span>  
  
 <span data-ttu-id="c3de4-342">Si supponga che due applicazioni, denominato prodotti e fornitori, ognuno ha un metodo denominato Sales.</span><span class="sxs-lookup"><span data-stu-id="c3de4-342">Suppose two applications, named Products and Suppliers, each has a method named Sales.</span></span> <span data-ttu-id="c3de4-343">Il metodo di vendite nell'applicazione prodotti fornisce il numero di identificazione (stock keeping unit o SKU) di un prodotto.</span><span class="sxs-lookup"><span data-stu-id="c3de4-343">The Sales method in the Products application provides the identification number (the stock keeping unit or SKU) of a product.</span></span> <span data-ttu-id="c3de4-344">Il metodo di vendite nell'applicazione fornitori fornisce il numero di identificazione, o SID, di un fornitore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-344">The Sales method in the Suppliers application provides the identification number, or SID, of a supplier.</span></span> <span data-ttu-id="c3de4-345">Di conseguenza, la convenzione di denominazione per questo esempio restituisce le chiavi, "Prodotti.vendite.SKU" e "Fornitori.vendite.SID".</span><span class="sxs-lookup"><span data-stu-id="c3de4-345">Consequently, the naming convention for this example yields the keys, "Products.Sales.SKU" and "Suppliers.Sales.SID".</span></span>  
  
## <a name="exploiting-key-conflicts"></a><span data-ttu-id="c3de4-346">Sfruttando i conflitti di chiave</span><span class="sxs-lookup"><span data-stu-id="c3de4-346">Exploiting Key Conflicts</span></span>  
 <span data-ttu-id="c3de4-347">Sfruttare i conflitti di chiave utilizzando la presenza di uno o più tasti speciali, preordinate per controllare l'elaborazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-347">Exploit key conflicts by using the presence of one or more special, prearranged keys to control processing.</span></span> <span data-ttu-id="c3de4-348">Si supponga che, in uno scenario, il gestore di eccezioni di livello più alto nella gerarchia di stack di chiamate intercetta tutte le eccezioni generate da gestori di eccezioni di livello inferiore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-348">Suppose, in one scenario, the highest level exception handler in the call stack hierarchy catches all exceptions thrown by lower-level exception handlers.</span></span> <span data-ttu-id="c3de4-349">Se esiste una coppia chiave/valore con una chiave speciale, il gestore di eccezioni di livello superiore formatta le coppie chiave/valore rimanenti nel <xref:System.Collections.IDictionary> oggetto in modalità non standard; in caso contrario, le coppie chiave/valore rimanenti vengono formattate in modo normale.</span><span class="sxs-lookup"><span data-stu-id="c3de4-349">If a key/value pair with a special key exists, the high-level exception handler formats the remaining key/value pairs in the <xref:System.Collections.IDictionary> object in some nonstandard way; otherwise, the remaining key/value pairs are formatted in some normal manner.</span></span>  
  
 <span data-ttu-id="c3de4-350">Si supponga ora che, in un altro scenario, il gestore di eccezioni a ogni livello della gerarchia dello stack di chiamate intercetta l'eccezione generata dal gestore di eccezioni di livello inferiore successivo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-350">Now suppose, in another scenario, the exception handler at each level of the call stack hierarchy catches the exception thrown by the next lower-level exception handler.</span></span> <span data-ttu-id="c3de4-351">Inoltre, ogni gestore eccezioni conosce la raccolta restituita dal <xref:System.Exception.Data%2A> proprietà contiene un set di coppie chiave/valore che è possibile accedere con un set di chiavi preordinato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-351">In addition, each exception handler knows the collection returned by the <xref:System.Exception.Data%2A> property contains a set of key/value pairs that can be accessed with a prearranged set of keys.</span></span>  
  
 <span data-ttu-id="c3de4-352">Ogni gestore eccezioni utilizza il set di chiavi preordinato per aggiornare il componente valore della coppia chiave/valore corrispondente con informazioni univoche per tale gestore di eccezioni.</span><span class="sxs-lookup"><span data-stu-id="c3de4-352">Each exception handler uses the prearranged set of keys to update the value component of the corresponding key/value pair with information unique to that exception handler.</span></span> <span data-ttu-id="c3de4-353">Al termine del processo di aggiornamento, il gestore di eccezioni genera l'eccezione al gestore di eccezioni di livello superiore successivo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-353">After the update process is complete, the exception handler throws the exception to the next higher-level exception handler.</span></span> <span data-ttu-id="c3de4-354">Infine, il gestore di eccezioni di livello più alto accede le coppie chiave/valore e visualizza le informazioni di aggiornamento consolidati da tutti i gestori di eccezioni di livello inferiore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-354">Finally, the highest level exception handler accesses the key/value pairs and displays the consolidated update information from all the lower-level exception handlers.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-355">Nell'esempio riportato di seguito viene illustrato come aggiungere e recuperare informazioni utilizzando il <xref:System.Exception.Data%2A> proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-355">The following example demonstrates how to add and retrieve information using the <xref:System.Exception.Data%2A> property.</span></span>  
  
 [!code-cpp[exception.data#1](~/samples/snippets/cpp/VS_Snippets_CLR/exception.data/CPP/data.cpp#1)]
 [!code-csharp[exception.data#1](~/samples/snippets/csharp/VS_Snippets_CLR/exception.data/CS/data.cs#1)]
 [!code-vb[exception.data#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/exception.data/VB/data.vb#1)]  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Collections.DictionaryEntry" />
      </Docs>
    </Member>
    <Member MemberName="GetBaseException">
      <MemberSignature Language="C#" Value="public virtual Exception GetBaseException ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig newslot virtual instance class System.Exception GetBaseException() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.GetBaseException" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Function GetBaseException () As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual Exception ^ GetBaseException();" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.GetBaseException</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-356">Quando ne viene eseguito l'override in una classe derivata, restituisce l'<see cref="T:System.Exception" /> che è la causa radice di una o più eccezioni successive.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-356">When overridden in a derived class, returns the <see cref="T:System.Exception" /> that is the root cause of one or more subsequent exceptions.</span>
          </span>
        </summary>
        <returns>
          <span data-ttu-id="c3de4-357">Eccezione generata per prima in una catena di eccezioni.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-357">The first exception thrown in a chain of exceptions.</span>
          </span>
          <span data-ttu-id="c3de4-358">Se la proprietà <see cref="P:System.Exception.InnerException" /> dell'eccezione corrente è un riferimento Null (<see langword="Nothing" /> in Visual Basic), restituisce l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-358">If the <see cref="P:System.Exception.InnerException" /> property of the current exception is a null reference (<see langword="Nothing" /> in Visual Basic), this property returns the current exception.</span>
          </span>
        </returns>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-359">Una catena di eccezioni consiste di un set di eccezioni in cui ogni eccezione nella catena è stata generata come risultato diretto di eccezione a cui fa riferimento il `InnerException` proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-359">A chain of exceptions consists of a set of exceptions such that each exception in the chain was thrown as a direct result of the exception referenced in its `InnerException` property.</span></span> <span data-ttu-id="c3de4-360">Per una determinata catena, può essere presente esattamente un'eccezione che è la causa radice di tutte le altre eccezioni nella catena.</span><span class="sxs-lookup"><span data-stu-id="c3de4-360">For a given chain, there can be exactly one exception that is the root cause of all other exceptions in the chain.</span></span> <span data-ttu-id="c3de4-361">Questa eccezione viene chiamata l'eccezione di base e il relativo `InnerException` proprietà contiene sempre un riferimento null.</span><span class="sxs-lookup"><span data-stu-id="c3de4-361">This exception is called the base exception and its `InnerException` property always contains a null reference.</span></span>  
  
 <span data-ttu-id="c3de4-362">Per tutte le eccezioni in una catena di eccezioni, il `GetBaseException` metodo deve restituire lo stesso oggetto (l'eccezione di base).</span><span class="sxs-lookup"><span data-stu-id="c3de4-362">For all exceptions in a chain of exceptions, the `GetBaseException` method must return the same object (the base exception).</span></span>  
  
 <span data-ttu-id="c3de4-363">Utilizzare il `GetBaseException` metodo quando si desidera individuare la causa radice di un'eccezione, ma non sono necessarie informazioni sulle eccezioni che potrebbero essersi verificate tra l'eccezione corrente e la prima eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-363">Use the `GetBaseException` method when you want to find the root cause of an exception but do not need information about exceptions that may have occurred between the current exception and the first exception.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-364">Esempio di codice seguente definisce due classi `Exception` classi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-364">The following code example defines two derived `Exception` classes.</span></span> <span data-ttu-id="c3de4-365">Forza un'eccezione e quindi genera nuovamente con ognuna delle classi derivate.</span><span class="sxs-lookup"><span data-stu-id="c3de4-365">It forces an exception and then throws it again with each of the derived classes.</span></span> <span data-ttu-id="c3de4-366">Il codice viene illustrato come utilizzare il `GetBaseException` metodo per recuperare l'eccezione originale.</span><span class="sxs-lookup"><span data-stu-id="c3de4-366">The code shows the use of the `GetBaseException` method to retrieve the original exception.</span></span>  
  
 [!code-cpp[System.Exception.GetBaseException#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.GetBaseException/CPP/getbaseexc.cpp#1)]
 [!code-csharp[System.Exception.GetBaseException#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.GetBaseException/CS/getbaseexc.cs#1)]
 [!code-vb[System.Exception.GetBaseException#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.GetBaseException/VB/getbaseexc.vb#1)]  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides">
          <para>
            <span data-ttu-id="c3de4-367">Il <see langword="GetBaseException" /> metodo viene sottoposto a override nelle classi che richiedono il controllo del contenuto di eccezione e formato.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-367">The <see langword="GetBaseException" /> method is overridden in classes that require control over the exception content or format.</span>
            </span>
          </para>
        </block>
      </Docs>
    </Member>
    <Member MemberName="GetObjectData">
      <MemberSignature Language="C#" Value="public virtual void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig newslot virtual instance void GetObjectData(class System.Runtime.Serialization.SerializationInfo info, valuetype System.Runtime.Serialization.StreamingContext context) cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Sub GetObjectData (info As SerializationInfo, context As StreamingContext)" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual void GetObjectData(System::Runtime::Serialization::SerializationInfo ^ info, System::Runtime::Serialization::StreamingContext context);" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)</InterfaceMember>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>System.Security.SecurityCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Void</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="info" Type="System.Runtime.Serialization.SerializationInfo" />
        <Parameter Name="context" Type="System.Runtime.Serialization.StreamingContext" />
      </Parameters>
      <Docs>
        <param name="info">
          <span data-ttu-id="c3de4-368">Oggetto <see cref="T:System.Runtime.Serialization.SerializationInfo" /> che contiene i dati oggetto serializzati relativi all'eccezione generata.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-368">The <see cref="T:System.Runtime.Serialization.SerializationInfo" /> that holds the serialized object data about the exception being thrown.</span>
          </span>
        </param>
        <param name="context">
          <span data-ttu-id="c3de4-369">Oggetto <see cref="T:System.Runtime.Serialization.StreamingContext" /> contenente le informazioni contestuali sull'origine o sulla destinazione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-369">The <see cref="T:System.Runtime.Serialization.StreamingContext" /> that contains contextual information about the source or destination.</span>
          </span>
        </param>
        <summary>
          <span data-ttu-id="c3de4-370">Quando ne viene eseguito l'override in una classe derivata, imposta il controllo <see cref="T:System.Runtime.Serialization.SerializationInfo" /> con le informazioni sull'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-370">When overridden in a derived class, sets the <see cref="T:System.Runtime.Serialization.SerializationInfo" /> with information about the exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-371">Il metodo `GetObjectData` imposta un oggetto <xref:System.Runtime.Serialization.SerializationInfo> con tutti i dati dell'oggetto eccezione destinati alla serializzazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-371">`GetObjectData` sets a <xref:System.Runtime.Serialization.SerializationInfo> with all the exception object data targeted for serialization.</span></span> <span data-ttu-id="c3de4-372">Durante la deserializzazione, l'oggetto eccezione viene ricostituito dall'oggetto `SerializationInfo` trasmesso sul flusso.</span><span class="sxs-lookup"><span data-stu-id="c3de4-372">During deserialization, the exception is reconstituted from the `SerializationInfo` transmitted over the stream.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-373">Esempio di codice seguente definisce una classe serializzabile `Exception` classe che implementa `GetObjectData`, che consente di modifiche non essenziali per due proprietà e quindi chiama la classe di base per eseguire la serializzazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-373">The following code example defines a derived serializable `Exception` class that implements `GetObjectData`, which makes minor changes to two properties and then calls the base class to perform the serialization.</span></span> <span data-ttu-id="c3de4-374">Nell'esempio impone un errore di divisione-0, quindi crea un'istanza dell'eccezione derivata.</span><span class="sxs-lookup"><span data-stu-id="c3de4-374">The example forces a divide-by-0 error and then creates an instance of the derived exception.</span></span> <span data-ttu-id="c3de4-375">Il codice di serializzazione dell'istanza in un file, il file viene deserializzato in una nuova eccezione, viene generata, quindi rileva e visualizza i dati dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-375">The code serializes the instance to a file, deserializes the file into a new exception, which it throws, and then catches and displays the exception's data.</span></span>  
  
 [!code-cpp[System.Exception.GetObjectData#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CPP/getobjdata.cpp#1)]
 [!code-csharp[System.Exception.GetObjectData#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.GetObjectData/CS/getobjdata.cs#1)]
 [!code-vb[System.Exception.GetObjectData#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.GetObjectData/VB/getobjdata.vb#1)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentNullException">
          <span data-ttu-id="c3de4-376">
            <paramref name="info" /> è un riferimento null (in Visual Basic <see langword="Nothing" />).</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-376">The <paramref name="info" /> parameter is a null reference (<see langword="Nothing" /> in Visual Basic).</span>
          </span>
        </exception>
        <permission cref="T:System.Security.SecurityCriticalAttribute">
          <span data-ttu-id="c3de4-377">richiede l'attendibilità totale per il chiamante immediato.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-377">requires full trust for the immediate caller.</span>
          </span>
          <span data-ttu-id="c3de4-378">Questo membro non può essere utilizzato da codice parzialmente attendibile o trasparente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-378">This member cannot be used by partially trusted or transparent code.</span>
          </span>
        </permission>
        <altmember cref="T:System.Runtime.Serialization.SerializationInfo" />
        <altmember cref="T:System.Runtime.Serialization.StreamingContext" />
      </Docs>
    </Member>
    <Member MemberName="GetType">
      <MemberSignature Language="C#" Value="public Type GetType ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig newslot virtual instance class System.Type GetType() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.GetType" />
      <MemberSignature Language="VB.NET" Value="Public Function GetType () As Type" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual Type ^ GetType();" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.GetType</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Type</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-379">Ottiene il tipo di runtime dell'istanza corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-379">Gets the runtime type of the current instance.</span>
          </span>
        </summary>
        <returns>
          <span data-ttu-id="c3de4-380">Oggetto <see cref="T:System.Type" /> che rappresenta il tipo runtime dell'istanza corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-380">A <see cref="T:System.Type" /> object that represents the exact runtime type of the current instance.</span>
          </span>
        </returns>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-381">Il <xref:System.Exception.GetType%2A> metodo supporta l'infrastruttura .NET Framework e internamente richiama il metodo fondamentale, <xref:System.Object.GetType%2A?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-381">The <xref:System.Exception.GetType%2A> method exists to support the .NET Framework infrastructure, and internally invokes the fundamental method, <xref:System.Object.GetType%2A?displayProperty=nameWithType>.</span></span>  
  
 ]]></format>
        </remarks>
        <altmember cref="T:System.Type" />
        <altmember cref="T:System.Object" />
      </Docs>
    </Member>
    <Member MemberName="HelpLink">
      <MemberSignature Language="C#" Value="public virtual string HelpLink { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string HelpLink" />
      <MemberSignature Language="DocId" Value="P:System.Exception.HelpLink" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Property HelpLink As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ HelpLink { System::String ^ get(); void set(System::String ^ value); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.HelpLink</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-382">Ottiene o imposta un collegamento al file della Guida associato all'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-382">Gets or sets a link to the help file associated with this exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-383">URN (Uniform Resource Name) o URL (Uniform Resource Locator).</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-383">The Uniform Resource Name (URN) or Uniform Resource Locator (URL).</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-384">Il valore restituito, che rappresenta un file della Guida, è un URN o URL.</span><span class="sxs-lookup"><span data-stu-id="c3de4-384">The return value, which represents a help file, is a URN or URL.</span></span> <span data-ttu-id="c3de4-385">Ad esempio, il `HelpLink` valore potrebbe essere:</span><span class="sxs-lookup"><span data-stu-id="c3de4-385">For example, the `HelpLink` value could be:</span></span>  
  
 <span data-ttu-id="c3de4-386">"file:///C:/Applications/Bazzal/help.html#ErrorNum42"</span><span class="sxs-lookup"><span data-stu-id="c3de4-386">"file:///C:/Applications/Bazzal/help.html#ErrorNum42"</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-387">Nell'esempio di codice riportato di seguito viene genera un `Exception` che imposta il `HelpLink` proprietà nel relativo costruttore e rileva l'eccezione e Visualizza `HelpLink`.</span><span class="sxs-lookup"><span data-stu-id="c3de4-387">The following code example throws an `Exception` that sets the `HelpLink` property in its constructor and then catches the exception and displays `HelpLink`.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="HResult">
      <MemberSignature Language="C#" Value="public int HResult { get; protected set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance int32 HResult" />
      <MemberSignature Language="DocId" Value="P:System.Exception.HResult" />
      <MemberSignature Language="VB.NET" Value="Public Property HResult As Integer" />
      <MemberSignature Language="C++ CLI" Value="public:  property int HResult {  public:&#xA;int get(); protected:&#xA; void set(int value); };" />
      <MemberType>Property</MemberType>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Int32</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-388">Ottiene o imposta HRESULT, un valore numerico codificato che viene assegnato a un'eccezione specifica.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-388">Gets or sets HRESULT, a coded numerical value that is assigned to a specific exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-389">Valore HRESULT.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-389">The HRESULT value.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-390">HRESULT è un valore a 32 bit, suddiviso in tre campi differenti: un codice di gravità, un codice di funzionalità e un codice di errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-390">HRESULT is a 32-bit value, divided into three different fields: a severity code, a facility code, and an error code.</span></span> <span data-ttu-id="c3de4-391">Il codice di gravità indica se il valore restituito rappresenta informazioni, avviso o errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-391">The severity code indicates whether the return value represents information, warning, or error.</span></span> <span data-ttu-id="c3de4-392">Il codice di funzionalità identifica l'area del sistema responsabile per l'errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-392">The facility code identifies the area of the system responsible for the error.</span></span> <span data-ttu-id="c3de4-393">Il codice di errore è un numero univoco assegnato per rappresentare l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-393">The error code is a unique number that is assigned to represent the exception.</span></span> <span data-ttu-id="c3de4-394">Ogni eccezione viene eseguito il mapping a un HRESULT distinto.</span><span class="sxs-lookup"><span data-stu-id="c3de4-394">Each exception is mapped to a distinct HRESULT.</span></span> <span data-ttu-id="c3de4-395">Quando il codice gestito genera un'eccezione, il runtime passa il valore HRESULT per il client COM.</span><span class="sxs-lookup"><span data-stu-id="c3de4-395">When managed code throws an exception, the runtime passes the HRESULT to the COM client.</span></span> <span data-ttu-id="c3de4-396">Quando il codice non gestito viene restituito un errore, HRESULT viene convertito in un'eccezione, che viene quindi generata dal runtime.</span><span class="sxs-lookup"><span data-stu-id="c3de4-396">When unmanaged code returns an error, the HRESULT is converted to an exception, which is then thrown by the runtime.</span></span> <span data-ttu-id="c3de4-397">Per informazioni sui valori HRESULT e le relative eccezioni corrispondente di .NET Framework, vedere [come: mappa di HRESULT ed eccezioni](~/docs/framework/interop/how-to-map-hresults-and-exceptions.md).</span><span class="sxs-lookup"><span data-stu-id="c3de4-397">For information about HRESULT values and their corresponding .NET Framework exceptions, see [How to: Map HRESULTs and Exceptions](~/docs/framework/interop/how-to-map-hresults-and-exceptions.md).</span></span> <span data-ttu-id="c3de4-398">Vedere [valori HRESULT comuni](http://msdn.microsoft.com/library/windows/desktop/aa378137.aspx) nella documentazione di Windows per un elenco dei valori di cui si è più probabile che si verifichino.</span><span class="sxs-lookup"><span data-stu-id="c3de4-398">See [Common HRESULT Values](http://msdn.microsoft.com/library/windows/desktop/aa378137.aspx) in the Windows documentation for a list of the values you are most likely to encounter.</span></span>  
  
 <span data-ttu-id="c3de4-399">A partire dal [!INCLUDE[net_v45](~/includes/net-v45-md.md)], <xref:System.Exception.HResult%2A> setter della proprietà è protetto, mentre il metodo di richiamo è pubblico.</span><span class="sxs-lookup"><span data-stu-id="c3de4-399">Starting with the [!INCLUDE[net_v45](~/includes/net-v45-md.md)], the <xref:System.Exception.HResult%2A> property's setter is protected, whereas its getter is public.</span></span>  <span data-ttu-id="c3de4-400">Nelle versioni precedenti di .NET Framework, sono protetti sia getter e setter.</span><span class="sxs-lookup"><span data-stu-id="c3de4-400">In previous versions of the .NET Framework, both getter and setter are protected.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-401">L'esempio di codice seguente definisce un oggetto derivato `Exception` classe che imposta il `HResult` proprietà su un valore personalizzato nel relativo costruttore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-401">The following code example defines a derived `Exception` class that sets the `HResult` property to a custom value in its constructor.</span></span>  
  
 [!code-cpp[System.Exception.HResult#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.HResult/CPP/hresult.cpp#1)]
 [!code-csharp[System.Exception.HResult#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.HResult/CS/hresult.cs#1)]
 [!code-vb[System.Exception.HResult#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.HResult/VB/hresult.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="InnerException">
      <MemberSignature Language="C#" Value="public Exception InnerException { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Exception InnerException" />
      <MemberSignature Language="DocId" Value="P:System.Exception.InnerException" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property InnerException As Exception" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property Exception ^ InnerException { Exception ^ get(); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.InnerException</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Exception</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-402">Ottiene l'istanza di <see cref="T:System.Exception" /> che ha causato l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-402">Gets the <see cref="T:System.Exception" /> instance that caused the current exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-403">Oggetto che descrive l'errore che ha causato l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-403">An object that describes the error that caused the current exception.</span>
          </span>
          <span data-ttu-id="c3de4-404">La proprietà <see cref="P:System.Exception.InnerException" /> restituisce lo stesso valore passato al costruttore <see cref="M:System.Exception.#ctor(System.String,System.Exception)" />, oppure <see langword="null" /> se il valore dell'eccezione interna non è stato fornito al costruttore.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-404">The <see cref="P:System.Exception.InnerException" /> property returns the same value as was passed into the <see cref="M:System.Exception.#ctor(System.String,System.Exception)" /> constructor, or <see langword="null" /> if the inner exception value was not supplied to the constructor.</span>
          </span>
          <span data-ttu-id="c3de4-405">Questa proprietà è di sola lettura.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-405">This property is read-only.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-406">Quando un'eccezione `X` viene generata come risultato diretto di un'eccezione precedente `Y`, <xref:System.Exception.InnerException%2A> proprietà di `X` deve contenere un riferimento a `Y`.</span><span class="sxs-lookup"><span data-stu-id="c3de4-406">When an exception `X` is thrown as a direct result of a previous exception `Y`, the <xref:System.Exception.InnerException%2A> property of `X` should contain a reference to `Y`.</span></span>  
  
 <span data-ttu-id="c3de4-407">Utilizzare la proprietà <xref:System.Exception.InnerException%2A> per ottenere il set di eccezioni che ha causato l'eccezione corrente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-407">Use the <xref:System.Exception.InnerException%2A> property to obtain the set of exceptions that led to the current exception.</span></span>  
  
 <span data-ttu-id="c3de4-408">È possibile creare una nuova eccezione che rileva un'eccezione precedente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-408">You can create a new exception that catches an earlier exception.</span></span> <span data-ttu-id="c3de4-409">Il codice che gestisce che la seconda eccezione è possibile apportare utilizzano le informazioni aggiuntive all'eccezione precedente per gestire l'errore in modo più appropriato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-409">The code that handles the second exception can make use of the additional information from the earlier exception to handle the error more appropriately.</span></span>  
  
 <span data-ttu-id="c3de4-410">Si supponga che una funzione che legge un file e formati di dati da tale file.</span><span class="sxs-lookup"><span data-stu-id="c3de4-410">Suppose that there is a function that reads a file and formats the data from that file.</span></span> <span data-ttu-id="c3de4-411">In questo esempio, quando si cerca di leggere il file, un <xref:System.IO.IOException> viene generata un'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-411">In this example, as the code tries to read the file, an <xref:System.IO.IOException> is thrown.</span></span> <span data-ttu-id="c3de4-412">La funzione intercetta il <xref:System.IO.IOException> e genera un <xref:System.IO.FileNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-412">The function catches the <xref:System.IO.IOException> and throws a <xref:System.IO.FileNotFoundException>.</span></span> <span data-ttu-id="c3de4-413">Il <xref:System.IO.IOException> in è stato possibile salvare il <xref:System.Exception.InnerException%2A> proprietà del <xref:System.IO.FileNotFoundException>, per attivare il codice che memorizza nella cache il <xref:System.IO.FileNotFoundException> per esaminare la causa dell'errore iniziale.</span><span class="sxs-lookup"><span data-stu-id="c3de4-413">The <xref:System.IO.IOException> could be saved in the <xref:System.Exception.InnerException%2A> property of the <xref:System.IO.FileNotFoundException>, enabling the code that catches the <xref:System.IO.FileNotFoundException> to examine the cause of the initial error.</span></span>  
  
 <span data-ttu-id="c3de4-414">Il <xref:System.Exception.InnerException%2A> , che contiene un riferimento all'eccezione interna, viene impostata al momento dell'inizializzazione dell'oggetto eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-414">The <xref:System.Exception.InnerException%2A> property, which holds a reference to the inner exception, is set upon initialization of the exception object.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-415">Nell'esempio riportato di seguito viene illustrato come generare e intercettare un'eccezione che fa riferimento all'eccezione interna.</span><span class="sxs-lookup"><span data-stu-id="c3de4-415">The following example demonstrates throwing and catching an exception that references an inner exception.</span></span>  
  
 [!code-cpp[InnerEx#1](~/samples/snippets/cpp/VS_Snippets_CLR/InnerEx/CPP/innerex.cpp#1)]
 [!code-csharp[InnerEx#1](~/samples/snippets/csharp/VS_Snippets_CLR/InnerEx/CS/innerex.cs#1)]
 [!code-vb[InnerEx#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/InnerEx/VB/innerex.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="Message">
      <MemberSignature Language="C#" Value="public virtual string Message { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string Message" />
      <MemberSignature Language="DocId" Value="P:System.Exception.Message" />
      <MemberSignature Language="VB.NET" Value="Public Overridable ReadOnly Property Message As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ Message { System::String ^ get(); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.Message</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-416">Ottiene un messaggio che descrive l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-416">Gets a message that describes the current exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-417">Messaggio di errore che spiega il motivo dell'eccezione o una stringa vuota ("").</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-417">The error message that explains the reason for the exception, or an empty string ("").</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-418">I messaggi di errore di destinazione lo sviluppatore che gestisce l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-418">Error messages target the developer who is handling the exception.</span></span> <span data-ttu-id="c3de4-419">Il testo del <xref:System.Exception.Message%2A> proprietà completamente deve descrivere l'errore e, se possibile, inoltre deve spiegare come correggere l'errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-419">The text of the <xref:System.Exception.Message%2A> property should completely describe the error and, when possible, should also explain how to correct the error.</span></span> <span data-ttu-id="c3de4-420">I gestori di eccezioni di livello superiore possono visualizzare il messaggio agli utenti finali, è quindi consigliabile verificare che sia grammatica corretta e che ogni frase del messaggio termina con un punto.</span><span class="sxs-lookup"><span data-stu-id="c3de4-420">Top-level exception handlers may display the message to end-users, so you should ensure that it is grammatically correct and that each sentence of the message ends with a period.</span></span> <span data-ttu-id="c3de4-421">Non utilizzare punti interrogativi o punti esclamativi.</span><span class="sxs-lookup"><span data-stu-id="c3de4-421">Do not use question marks or exclamation points.</span></span> <span data-ttu-id="c3de4-422">Se l'applicazione utilizza i messaggi di eccezione localizzata, è necessario assicurarsi che questi valori vengono convertiti in modo accurato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-422">If your application uses localized exception messages, you should ensure that they are accurately translated.</span></span>  
  
> [!IMPORTANT]
>  <span data-ttu-id="c3de4-423">Non divulgare informazioni riservate nei messaggi di eccezione senza verificare la presenza delle autorizzazioni appropriate.</span><span class="sxs-lookup"><span data-stu-id="c3de4-423">Do not disclose sensitive information in exception messages without checking for the appropriate permissions.</span></span>  
  
 <span data-ttu-id="c3de4-424">Il valore di <xref:System.Exception.Message%2A> proprietà sia presenti le informazioni restituite da <xref:System.Exception.ToString%2A>. Il <xref:System.Exception.Message%2A> proprietà viene impostata solo quando si crea un <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-424">The value of the <xref:System.Exception.Message%2A> property is included in the information returned by <xref:System.Exception.ToString%2A>.The <xref:System.Exception.Message%2A> property is set only when creating an <xref:System.Exception>.</span></span> <span data-ttu-id="c3de4-425">Se nessun messaggio è stato fornito al costruttore per l'istanza corrente, il sistema fornisce un messaggio predefinito che viene formattato utilizzando la lingua corrente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-425">If no message was supplied to the constructor for the current instance, the system supplies a default message that is formatted using the current system culture.</span></span>  
  
## <a name="windows-runtime-and-includenetv451includesnet-v451-mdmd"></a><span data-ttu-id="c3de4-426">Windows Runtime e [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span><span class="sxs-lookup"><span data-stu-id="c3de4-426">Windows Runtime and [!INCLUDE[net_v451](~/includes/net-v451-md.md)]</span></span>  
 <span data-ttu-id="c3de4-427">A partire dal [!INCLUDE[net_v451](~/includes/net-v451-md.md)] e [!INCLUDE[win81](~/includes/win81-md.md)], è stata migliorata la fedeltà dei messaggi di errore da eccezioni che vengono propagati da tipi di Windows Runtime e i membri che non fanno parte di .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="c3de4-427">Starting with the [!INCLUDE[net_v451](~/includes/net-v451-md.md)] and [!INCLUDE[win81](~/includes/win81-md.md)], the fidelity of error messages from exceptions that are propagated from Windows Runtime types and members that are not part of the .NET Framework is improved.</span></span> <span data-ttu-id="c3de4-428">In particolare, i messaggi di eccezione da estensioni del componente Visual C++ (C + + CX) ora vengono propagate in .NET Framework <xref:System.Exception> oggetti.</span><span class="sxs-lookup"><span data-stu-id="c3de4-428">In particular, exception messages from Visual C++ component extensions (C++/CX) are now propagated back into .NET Framework <xref:System.Exception> objects.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-429">Esempio di codice seguente genera un'eccezione e quindi rileva un <xref:System.Exception> eccezione e viene visualizzato il testo dell'eccezione del messaggio utilizzando il <xref:System.Exception.Message%2A> proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-429">The following code example throws and then catches an <xref:System.Exception> exception and displays the exception's text message using the <xref:System.Exception.Message%2A> property.</span></span>
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides">
          <para>
            <span data-ttu-id="c3de4-430">Se si genera un'eccezione da una proprietà, ed è necessario fare riferimento nel testo del <see cref="P:System.Exception.Message" /> all'argomento della proprietà che impostano oppure ottengono, utilizzare "value" come nome dell'argomento della proprietà.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-430">If you throw an exception from a property, and you need to refer in the text of <see cref="P:System.Exception.Message" /> to the property argument that you set or get, use "value" as the name of the property argument.</span>
            </span>
          </para>
        </block>
        <block subset="none" type="overrides">
          <para>
            <span data-ttu-id="c3de4-431">Il <see cref="P:System.Exception.Message" /> viene eseguito l'override di proprietà nelle classi che richiedono il controllo del contenuto del messaggio e del formato.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-431">The <see cref="P:System.Exception.Message" /> property is overridden in classes that require control over message content or format.</span>
            </span>
            <span data-ttu-id="c3de4-432">In genere il codice dell'applicazione accede a questa proprietà quando è necessario visualizzare informazioni su un'eccezione che è stata intercettata.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-432">Application code typically accesses this property when it needs to display information about an exception that has been caught.</span>
            </span>
            <span data-ttu-id="c3de4-433">Il messaggio di errore deve essere localizzato.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-433">The error message should be localized.</span>
            </span>
          </para>
        </block>
      </Docs>
    </Member>
    <Member MemberName="SerializeObjectState">
      <MemberSignature Language="C#" Value="protected event EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt; SerializeObjectState;" />
      <MemberSignature Language="ILAsm" Value=".event class System.EventHandler`1&lt;class System.Runtime.Serialization.SafeSerializationEventArgs&gt; SerializeObjectState" />
      <MemberSignature Language="DocId" Value="E:System.Exception.SerializeObjectState" />
      <MemberSignature Language="VB.NET" Value="Protected Custom Event SerializeObjectState As EventHandler(Of SafeSerializationEventArgs) " />
      <MemberSignature Language="C++ CLI" Value="protected:&#xA; event EventHandler&lt;System::Runtime::Serialization::SafeSerializationEventArgs ^&gt; ^ SerializeObjectState;" />
      <MemberType>Event</MemberType>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt;</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-434">Si verifica quando un'eccezione viene serializzata per creare un oggetto di stato eccezione contenente i dati serializzati relativi all'eccezione.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-434">Occurs when an exception is serialized to create an exception state object that contains serialized data about the exception.</span>
          </span>
        </summary>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-435">Implementa l'oggetto di stato di eccezione di <xref:System.Runtime.Serialization.ISafeSerializationData> interfaccia.</span><span class="sxs-lookup"><span data-stu-id="c3de4-435">The exception state object implements the <xref:System.Runtime.Serialization.ISafeSerializationData> interface.</span></span>  
  
 <span data-ttu-id="c3de4-436">Quando il <xref:System.Exception.SerializeObjectState> si sottoscrive l'evento, l'eccezione viene deserializzato e creato come un'eccezione vuota.</span><span class="sxs-lookup"><span data-stu-id="c3de4-436">When the <xref:System.Exception.SerializeObjectState> event is subscribed to, the exception is deserialized and created as an empty exception.</span></span> <span data-ttu-id="c3de4-437">Il costruttore dell'eccezione non viene eseguito e lo stato di eccezione anche viene deserializzato.</span><span class="sxs-lookup"><span data-stu-id="c3de4-437">The exception's constructor is not run, and the exception state is also deserialized.</span></span> <span data-ttu-id="c3de4-438">Il <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A> il metodo di callback dell'oggetto di stato eccezione riceve una notifica in modo da poter inserire i dati deserializzati nell'eccezione vuota.</span><span class="sxs-lookup"><span data-stu-id="c3de4-438">The <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A> callback method of the exception state object is then notified so that it can push deserialized data into the empty exception.</span></span>  
  
 <span data-ttu-id="c3de4-439">Il <xref:System.Exception.SerializeObjectState> evento consente ai tipi di eccezione trasparenti serializzare e deserializzare i dati dell'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-439">The <xref:System.Exception.SerializeObjectState> event enables transparent exception types to serialize and deserialize exception data.</span></span> <span data-ttu-id="c3de4-440">Il codice Transparent può eseguire i comandi all'interno del set di autorizzazioni che funziona all'interno, ma non è possibile eseguire, chiamare, derivare da o contenere codice critico.</span><span class="sxs-lookup"><span data-stu-id="c3de4-440">Transparent code can execute commands within the bounds of the permission set it is operating within, but cannot execute, call, derive from, or contain critical code.</span></span>  
  
 <span data-ttu-id="c3de4-441">Se il <xref:System.Exception.SerializeObjectState> evento non ha sottoscritto, la deserializzazione vengono eseguite come di consueto utilizzando il <xref:System.Exception.%23ctor%2A> costruttore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-441">If the <xref:System.Exception.SerializeObjectState> event is not subscribed to, deserialization occurs as usual using the <xref:System.Exception.%23ctor%2A> constructor.</span></span>  
  
 <span data-ttu-id="c3de4-442">In genere, un gestore per il <xref:System.Exception.SerializeObjectState> nel costruttore dell'eccezione per fornire per la propria serializzazione viene aggiunto l'evento.</span><span class="sxs-lookup"><span data-stu-id="c3de4-442">Typically, a handler for the <xref:System.Exception.SerializeObjectState> event is added in the exception's constructor to provide for its serialization.</span></span> <span data-ttu-id="c3de4-443">Tuttavia, poiché il costruttore non è eseguito quando il <xref:System.Exception.SerializeObjectState> gestore eventi viene eseguito, la serializzazione di un'eccezione deserializzata può generare un <xref:System.Runtime.Serialization.SerializationException> eccezione quando si tenta di deserializzare l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-443">But because the constructor is not executed when the <xref:System.Exception.SerializeObjectState> event handler executes, serializing a deserialized exception can throw a <xref:System.Runtime.Serialization.SerializationException> exception when you try to deserialize the exception.</span></span> <span data-ttu-id="c3de4-444">Per evitare questo problema, è inoltre necessario aggiungere il gestore per il <xref:System.Exception.SerializeObjectState> evento nel <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType> metodo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-444">To avoid this, you should also add the handler for the <xref:System.Exception.SerializeObjectState> event in the <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType> method.</span></span> <span data-ttu-id="c3de4-445">Vedere la sezione esempi per un'illustrazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-445">See the Examples section for an illustration.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-446">L'esempio seguente definisce un `BadDivisionException` che gestisce il <xref:System.Exception.SerializeObjectState> evento.</span><span class="sxs-lookup"><span data-stu-id="c3de4-446">The following example defines a `BadDivisionException` that handles the <xref:System.Exception.SerializeObjectState> event.</span></span> <span data-ttu-id="c3de4-447">Contiene inoltre un oggetto di stato, annidata struttura denominata `BadDivisionExceptionState` che implementa il <xref:System.Runtime.Serialization.ISafeSerializationData> interfaccia.</span><span class="sxs-lookup"><span data-stu-id="c3de4-447">It also contains a state object, which is a nested structure named `BadDivisionExceptionState` that implements the <xref:System.Runtime.Serialization.ISafeSerializationData> interface.</span></span>  
  
 [!code-csharp[System.Exception.SerializeObjectState#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.serializeobjectstate/cs/example2.cs#1)]
 [!code-vb[System.Exception.SerializeObjectState#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.serializeobjectstate/vb/example2.vb#1)]  
  
 <span data-ttu-id="c3de4-448">Il `BadDivisionException` eccezione viene generata quando si verifica una divisione a virgola mobile per zero.</span><span class="sxs-lookup"><span data-stu-id="c3de4-448">The `BadDivisionException` exception is thrown when a floating-point division by zero occurs.</span></span> <span data-ttu-id="c3de4-449">Durante la prima divisione per zero, l'esempio crea un'istanza di un `BadDivisionException` serializza l'oggetto, e genera l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-449">During the first division by zero, the example instantiates a `BadDivisionException` object, serializes it, and throws the exception.</span></span> <span data-ttu-id="c3de4-450">Quando si verificano successive divisioni per zero, l'esempio deserializza l'oggetto serializzato in precedenza, riserializza e genera l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-450">When subsequent divisions by zero occur, the example deserializes the  previously serialized object, reserializes it, and throws the exception.</span></span> <span data-ttu-id="c3de4-451">Per fornire per la serializzazione di oggetti, la deserializzazione, riserializzazione e la deserializzazione, l'esempio aggiunge il <xref:System.Exception.SerializeObjectState> gestore dell'evento sia nel `BadDivisionException` costruttore di classe e il <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType> implementazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-451">To provide for object serialization, deserialization, reserialization, and deserialization, the example adds the <xref:System.Exception.SerializeObjectState> event handler both in the `BadDivisionException` class constructor and in the <xref:System.Runtime.Serialization.ISafeSerializationData.CompleteDeserialization%2A?displayProperty=nameWithType> implementation.</span></span>  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides">
          <para>
            <span data-ttu-id="c3de4-452">Se questo evento è sottoscritto e, tutti i tipi derivati che seguono nella gerarchia di ereditarietà devono implementare lo stesso meccanismo di serializzazione.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-452">If this event is subscribed to and used, all derived types that follow in the inheritance hierarchy must implement the same serialization mechanism.</span>
            </span>
          </para>
        </block>
      </Docs>
    </Member>
    <Member MemberName="Source">
      <MemberSignature Language="C#" Value="public virtual string Source { get; set; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string Source" />
      <MemberSignature Language="DocId" Value="P:System.Exception.Source" />
      <MemberSignature Language="VB.NET" Value="Public Overridable Property Source As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ Source { System::String ^ get(); void set(System::String ^ value); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.Source</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-453">Ottiene o imposta il nome dell'oggetto o dell'applicazione che ha generato l'errore.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-453">Gets or sets the name of the application or the object that causes the error.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-454">Nome dell'oggetto che ha generato l'errore.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-454">The name of the application or the object that causes the error.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-455">Se il <xref:System.Exception.Source%2A> non è impostata in modo esplicito, il runtime imposta automaticamente il nome dell'assembly in cui è stata generata l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-455">If the <xref:System.Exception.Source%2A> property is not set explicitly, the runtime automatically sets it to the name of the assembly in which the exception originated.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-456">Nell'esempio seguente genera un `Exception` che imposta il `Source` proprietà nel relativo costruttore e rileva l'eccezione e la Visualizza `Source`.</span><span class="sxs-lookup"><span data-stu-id="c3de4-456">The following example throws an `Exception` that sets the `Source` property in its constructor and then catches the exception and displays `Source`.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
        <exception cref="T:System.ArgumentException">
          <span data-ttu-id="c3de4-457">L'oggetto deve essere un oggetto <see cref="N:System.Reflection" /> di runtime.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-457">The object must be a runtime <see cref="N:System.Reflection" /> object</span>
          </span>
        </exception>
      </Docs>
    </Member>
    <Member MemberName="StackTrace">
      <MemberSignature Language="C#" Value="public virtual string StackTrace { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance string StackTrace" />
      <MemberSignature Language="DocId" Value="P:System.Exception.StackTrace" />
      <MemberSignature Language="VB.NET" Value="Public Overridable ReadOnly Property StackTrace As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; virtual property System::String ^ StackTrace { System::String ^ get(); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.StackTrace</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-458">Ottiene una rappresentazione di stringa dei frame immediati nello stack di chiamate.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-458">Gets a string representation of the immediate frames on the call stack.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-459">Stringa in cui vengono descritti i frame immediati dello stack di chiamate.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-459">A string that describes the immediate frames of the call stack.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-460">Lo stack di esecuzione tiene traccia di tutti i metodi in esecuzione in un determinato istante.</span><span class="sxs-lookup"><span data-stu-id="c3de4-460">The execution stack keeps track of all the methods that are in execution at a given instant.</span></span> <span data-ttu-id="c3de4-461">La traccia delle chiamate ai metodi viene denominata traccia dello stack.</span><span class="sxs-lookup"><span data-stu-id="c3de4-461">A trace of the method calls is called a stack trace.</span></span> <span data-ttu-id="c3de4-462">La voce di traccia di stack consente di seguire lo stack di chiamate per il numero di riga nel metodo in cui si verifica l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-462">The stack trace listing provides a way to follow the call stack to the line number in the method where the exception occurs.</span></span>  
  
 <span data-ttu-id="c3de4-463">Il <xref:System.Exception.StackTrace%2A> proprietà restituisce i frame dello stack di chiamate che hanno origine in corrispondenza della posizione in cui è stata generata l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-463">The <xref:System.Exception.StackTrace%2A> property returns the frames of the call stack that originate at the location where the exception was thrown.</span></span> <span data-ttu-id="c3de4-464">È possibile ottenere informazioni sui frame aggiuntivi nello stack di chiamate creando una nuova istanza di <xref:System.Diagnostics.StackTrace?displayProperty=nameWithType> classe e l'utilizzo di relativo <xref:System.Diagnostics.StackTrace.ToString%2A?displayProperty=nameWithType> (metodo).</span><span class="sxs-lookup"><span data-stu-id="c3de4-464">You can obtain information about additional frames in the call stack by creating a new instance of the <xref:System.Diagnostics.StackTrace?displayProperty=nameWithType> class and using its <xref:System.Diagnostics.StackTrace.ToString%2A?displayProperty=nameWithType> method.</span></span>  
  
 <span data-ttu-id="c3de4-465">Common language runtime (CLR) aggiorna la traccia dello stack ogni volta che viene generata un'eccezione nel codice dell'applicazione (tramite il `throw` parola chiave).</span><span class="sxs-lookup"><span data-stu-id="c3de4-465">The common language runtime (CLR) updates the stack trace whenever an exception is thrown in application code (by using the `throw` keyword).</span></span> <span data-ttu-id="c3de4-466">Se l'eccezione è stata rigenerata in un metodo che è diverso da quello in cui è stata inizialmente generata, la traccia stack contiene il percorso nel metodo in cui è stata inizialmente generata l'eccezione e la posizione nel metodo in cui è stata l'eccezione generata di nuovo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-466">If the exception was rethrown in a method that is different than the method where it was originally thrown, the stack trace contains both the location in the method where the exception was originally thrown, and the location in the method where the exception was rethrown.</span></span> <span data-ttu-id="c3de4-467">Se l'eccezione viene generata un'eccezione e in seguito rigenerata nello stesso metodo, la traccia stack contiene solo il percorso in cui è stata rigenerata l'eccezione e non include il percorso in cui è stata inizialmente generata l'eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-467">If the exception is thrown, and later rethrown, in the same method, the stack trace only contains the location where the exception was rethrown and does not include the location where the exception was originally thrown.</span></span>  
  
 <span data-ttu-id="c3de4-468">Il <xref:System.Exception.StackTrace%2A> proprietà potrebbe non restituire il numero di chiamate di metodo come previsto a causa di trasformazioni di codice, ad esempio l'incorporamento, che si verificano durante l'ottimizzazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-468">The <xref:System.Exception.StackTrace%2A> property may not report as many method calls as expected because of code transformations, such as inlining, that occur during optimization.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-469">Nell'esempio di codice riportato di seguito viene genera un `Exception` rileva e consente di visualizzare una traccia dello stack utilizzando il `StackTrace` proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-469">The following code example throws an `Exception` and then catches it and displays a stack trace using the `StackTrace` property.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
        <block subset="none" type="overrides">
          <para>
            <span data-ttu-id="c3de4-470">Il <see langword="StackTrace" /> viene eseguito l'override di proprietà nelle classi che richiedono il controllo del contenuto della traccia dello stack e formato.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-470">The <see langword="StackTrace" /> property is overridden in classes that require control over the stack trace content or format.</span>
            </span>
            <span data-ttu-id="c3de4-471">Per impostazione predefinita, la traccia dello stack verrà acquisita immediatamente prima di un oggetto eccezione viene generato.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-471">By default, the stack trace is captured immediately before an exception object is thrown.</span>
            </span>
            <span data-ttu-id="c3de4-472">Utilizzare <see cref="P:System.Environment.StackTrace" /> per ottenere informazioni sulla traccia dello stack quando non viene generata alcuna eccezione.</span>
            <span class="sxs-lookup">
              <span data-stu-id="c3de4-472">Use <see cref="P:System.Environment.StackTrace" /> to get stack trace information when no exception is being thrown.</span>
            </span>
          </para>
        </block>
        <altmember cref="P:System.Environment.StackTrace" />
      </Docs>
    </Member>
    <Member MemberName="TargetSite">
      <MemberSignature Language="C#" Value="public System.Reflection.MethodBase TargetSite { get; }" />
      <MemberSignature Language="ILAsm" Value=".property instance class System.Reflection.MethodBase TargetSite" />
      <MemberSignature Language="DocId" Value="P:System.Exception.TargetSite" />
      <MemberSignature Language="VB.NET" Value="Public ReadOnly Property TargetSite As MethodBase" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; property System::Reflection::MethodBase ^ TargetSite { System::Reflection::MethodBase ^ get(); };" />
      <MemberType>Property</MemberType>
      <Implements>
        <InterfaceMember>P:System.Runtime.InteropServices._Exception.TargetSite</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <Attributes>
        <Attribute>
          <AttributeName>get: System.Security.SecuritySafeCritical</AttributeName>
        </Attribute>
      </Attributes>
      <ReturnValue>
        <ReturnType>System.Reflection.MethodBase</ReturnType>
      </ReturnValue>
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-473">Ottiene il metodo che genera l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-473">Gets the method that throws the current exception.</span>
          </span>
        </summary>
        <value>
          <span data-ttu-id="c3de4-474">Oggetto <see cref="T:System.Reflection.MethodBase" /> che ha generato l'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-474">The <see cref="T:System.Reflection.MethodBase" /> that threw the current exception.</span>
          </span>
        </value>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-475">Se il metodo che genera questa eccezione non è disponibile e la traccia dello stack non è un riferimento null (`Nothing` in Visual Basic), <xref:System.Exception.TargetSite%2A> otterrà il metodo dalla traccia dello stack.</span><span class="sxs-lookup"><span data-stu-id="c3de4-475">If the method that throws this exception is not available and the stack trace is not a null reference (`Nothing` in Visual Basic), <xref:System.Exception.TargetSite%2A> obtains the method from the stack trace.</span></span> <span data-ttu-id="c3de4-476">Se la traccia dello stack è un riferimento null, la proprietà <xref:System.Exception.TargetSite%2A> restituirà un riferimento null.</span><span class="sxs-lookup"><span data-stu-id="c3de4-476">If the stack trace is a null reference, <xref:System.Exception.TargetSite%2A> also returns a null reference.</span></span>  
  
> [!NOTE]
>  <span data-ttu-id="c3de4-477">Il <xref:System.Exception.TargetSite%2A> proprietà potrebbe non segnalare con precisione il nome del metodo in cui è stata generata un'eccezione se il gestore di eccezioni gestisce l'eccezione attraverso i limiti del dominio applicazione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-477">The <xref:System.Exception.TargetSite%2A> property may not accurately report the name of the method in which an exception was thrown if the exception handler handles an exception across application domain boundaries.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-478">Nell'esempio di codice riportato di seguito viene genera un `Exception` rileva e visualizza il metodo origine usando il `TargetSite` proprietà.</span><span class="sxs-lookup"><span data-stu-id="c3de4-478">The following code example throws an `Exception` and then catches it and displays the originating method using the `TargetSite` property.</span></span>  
  
 [!code-cpp[System.Exception.Properties#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.Exception.Properties/CPP/properties.cpp#1)]
 [!code-csharp[System.Exception.Properties#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.Exception.Properties/CS/properties.cs#1)]
 [!code-vb[System.Exception.Properties#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.Exception.Properties/VB/properties.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
    <Member MemberName="ToString">
      <MemberSignature Language="C#" Value="public override string ToString ();" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig virtual instance string ToString() cil managed" />
      <MemberSignature Language="DocId" Value="M:System.Exception.ToString" />
      <MemberSignature Language="VB.NET" Value="Public Overrides Function ToString () As String" />
      <MemberSignature Language="C++ CLI" Value="public:&#xA; override System::String ^ ToString();" />
      <MemberType>Method</MemberType>
      <Implements>
        <InterfaceMember>M:System.Runtime.InteropServices._Exception.ToString</InterfaceMember>
      </Implements>
      <AssemblyInfo>
        <AssemblyName>System.Runtime</AssemblyName>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
        <AssemblyVersion>4.0.10.0</AssemblyVersion>
        <AssemblyVersion>4.0.20.0</AssemblyVersion>
        <AssemblyVersion>4.1.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.0.0</AssemblyVersion>
        <AssemblyVersion>4.2.1.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>mscorlib</AssemblyName>
        <AssemblyVersion>2.0.5.0</AssemblyVersion>
        <AssemblyVersion>4.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <AssemblyInfo>
        <AssemblyName>netstandard</AssemblyName>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.String</ReturnType>
      </ReturnValue>
      <Parameters />
      <Docs>
        <summary>
          <span data-ttu-id="c3de4-479">Crea e restituisce una rappresentazione di stringa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-479">Creates and returns a string representation of the current exception.</span>
          </span>
        </summary>
        <returns>
          <span data-ttu-id="c3de4-480">Una rappresentazione di stringa dell'eccezione corrente.</span>
          <span class="sxs-lookup">
            <span data-stu-id="c3de4-480">A string representation of the current exception.</span>
          </span>
        </returns>
        <remarks>
          <format type="text/markdown"><![CDATA[  
  
## Remarks  
 <span data-ttu-id="c3de4-481"><xref:System.Exception.ToString%2A> Restituisce una rappresentazione dell'eccezione corrente che deve essere facilmente comprensibile.</span><span class="sxs-lookup"><span data-stu-id="c3de4-481"><xref:System.Exception.ToString%2A> returns a representation of the current exception that is intended to be understood by humans.</span></span> <span data-ttu-id="c3de4-482">Se l'eccezione contiene dati dipendenti dalle impostazioni cultura, la rappresentazione di stringa restituito da `ToString` è necessaria per prendere in considerazione le impostazioni cultura correnti.</span><span class="sxs-lookup"><span data-stu-id="c3de4-482">Where the exception contains culture-sensitive data, the string representation returned by `ToString` is required to take into account the current system culture.</span></span> <span data-ttu-id="c3de4-483">Anche se non sono previsti requisiti esatti per il formato della stringa restituita, consigliabile tentare di riflette il valore dell'oggetto come percepito dall'utente.</span><span class="sxs-lookup"><span data-stu-id="c3de4-483">Although there are no exact requirements for the format of the returned string, it should attempt to reflect the value of the object as perceived by the user.</span></span>  
  
 <span data-ttu-id="c3de4-484">L'implementazione predefinita di <xref:System.Exception.ToString%2A> Ottiene il nome della classe che ha generato l'eccezione corrente, il messaggio, il risultato della chiamata al metodo <xref:System.Exception.ToString%2A> l'eccezione interna e il risultato della chiamata <xref:System.Environment.StackTrace%2A?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-484">The default implementation of <xref:System.Exception.ToString%2A> obtains the name of the class that threw the current exception, the message, the result of calling <xref:System.Exception.ToString%2A> on the inner exception, and the result of calling <xref:System.Environment.StackTrace%2A?displayProperty=nameWithType>.</span></span> <span data-ttu-id="c3de4-485">Se uno di questi membri è `null`, il relativo valore non è incluso nella stringa restituita.</span><span class="sxs-lookup"><span data-stu-id="c3de4-485">If any of these members is `null`, its value is not included in the returned string.</span></span>  
  
 <span data-ttu-id="c3de4-486">Se nessun messaggio di errore o se è una stringa vuota (""), quindi viene restituito alcun messaggio di errore.</span><span class="sxs-lookup"><span data-stu-id="c3de4-486">If there is no error message or if it is an empty string (""), then no error message is returned.</span></span> <span data-ttu-id="c3de4-487">Il nome dell'eccezione interna e la traccia dello stack vengono restituiti solo se non sono `null`.</span><span class="sxs-lookup"><span data-stu-id="c3de4-487">The name of the inner exception and the stack trace are returned only if they are not `null`.</span></span>  
  
 <span data-ttu-id="c3de4-488">Questo metodo esegue l'override del metodo <xref:System.Object.ToString%2A?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="c3de4-488">This method overrides <xref:System.Object.ToString%2A?displayProperty=nameWithType>.</span></span>  
  
   
  
## Examples  
 <span data-ttu-id="c3de4-489">Nell'esempio seguente genera un'eccezione e viene visualizzato il risultato della chiamata al metodo <xref:System.Exception.ToString%2A> in tale eccezione.</span><span class="sxs-lookup"><span data-stu-id="c3de4-489">The following example causes an exception and displays the result of calling <xref:System.Exception.ToString%2A> on that exception.</span></span> <span data-ttu-id="c3de4-490">Si noti che il <xref:System.Exception.ToString%2A?displayProperty=nameWithType> metodo viene chiamato in modo implicito quando l'istanza di classe di eccezione viene visualizzata nell'elenco di argomenti del <xref:System.Console.WriteLine%2A?displayProperty=nameWithType> metodo.</span><span class="sxs-lookup"><span data-stu-id="c3de4-490">Note that the <xref:System.Exception.ToString%2A?displayProperty=nameWithType> method is called implicitly when the Exception class instance appears in the argument list of the <xref:System.Console.WriteLine%2A?displayProperty=nameWithType> method.</span></span>  
  
 [!code-cpp[System.Exception.ToString#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.exception.tostring/cpp/ToStringEx1.cpp#1)]
 [!code-csharp[System.Exception.ToString#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.exception.tostring/cs/ToStringEx1.cs#1)]
 [!code-vb[System.Exception.ToString#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.exception.tostring/vb/ToStringEx1.vb#1)]  
  
 ]]></format>
        </remarks>
      </Docs>
    </Member>
  </Members>
</Type>