<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="CommunicationObjectFaultedException.xml" source-language="en-US" target-language="it-IT">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac557c99eda85bfe1934ce64cb71bbd648cc444d94a.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">57c99eda85bfe1934ce64cb71bbd648cc444d94a</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>The exception that is thrown when a call is made to a communication object that has faulted.</source>
          <target state="translated">Eccezione generata quando si effettua una chiamata a un oggetto di comunicazione per cui si è verificato un errore.</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>A <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> is thrown when a call is made to a faulted communication object.</source>
          <target state="translated">Eccezione <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> generata quando si effettua una chiamata a un oggetto di comunicazione per cui si è verificato un errore.</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source><ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> is a derived class of <ph id="ph2">&lt;xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType&gt;</ph> and can occur in correct applications.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> è una classe derivata di <ph id="ph2">&lt;xref:System.ServiceModel.CommunicationException?displayProperty=nameWithType&gt;</ph> e rappresenta eccezioni che possono verificarsi nelle applicazioni corrette.</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>Because typically the code that calls the <ph id="ph1">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> method reports the error condition that caused the call to <ph id="ph2">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph>, this exception indicates that the call failed but the most useful error information is elsewhere.</source>
          <target state="translated">Poiché in genere il codice che chiama il metodo <ph id="ph1">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph> segnala la condizione di errore che ha provocato la chiamata al metodo <ph id="ph2">&lt;xref:System.ServiceModel.ICommunicationObject.Abort%2A?displayProperty=nameWithType&gt;</ph>, l'eccezione indica che la chiamata ha avuto esito negativo. Tuttavia, le informazioni più utili sull'errore sono altrove.</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>If an object is faulted with several pending calls, only one call throws a specific exception; the others throw <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</source>
          <target state="translated">Se un oggetto in cui si è verificato un errore presenta molte chiamate in sospeso, solo una chiamata genera un'eccezione specifica, mentre tutte le altre generano l'eccezione <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="T:System.ServiceModel.CommunicationObjectFaultedException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class.</source>
          <target state="translated">Inizializza una nuova istanza della classe <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class.</source>
          <target state="translated">Inizializza una nuova istanza della classe <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</source>
          <target state="translated">Crea un nuovo oggetto <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph>.</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          <target state="translated">Messaggio in cui viene descritta l'eccezione.</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class using the specified message.</source>
          <target state="translated">Consente di inizializzare una nuova istanza della classe <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> utilizzando il messaggio specificato.</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String)">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> using the specified <ph id="ph2">`message`</ph>.</source>
          <target state="translated">Consente di creare un nuovo oggetto <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> utilizzando il parametro <ph id="ph2">`message`</ph> specificato.</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The serialization information used to create the exception object.</source>
          <target state="translated">Informazioni di serializzazione utilizzate per creare l'oggetto eccezione.</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The context within which the exception object is created.</source>
          <target state="translated">Contesto in cui viene creato l'oggetto eccezione.</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class when deserializing a stream using the specified <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> and <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> objects.</source>
          <target state="translated">Consente di inizializzare una nuova istanza della classe <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> quando si deserializza un flusso utilizzando gli oggetti <ph id="ph2">&lt;see cref="T:System.Runtime.Serialization.SerializationInfo" /&gt;</ph> e <ph id="ph3">&lt;see cref="T:System.Runtime.Serialization.StreamingContext" /&gt;</ph> specificati.</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>This constructor is called when deserializing a <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> object from a stream.</source>
          <target state="translated">Questo costruttore viene chiamato quando si deserializza un oggetto <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> a partire da un flusso.</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>The exception message.</source>
          <target state="translated">Messaggio dell'eccezione.</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>The inner exception.</source>
          <target state="translated">Eccezione interna.</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> class using the specified message and inner exception.</source>
          <target state="translated">Consente di inizializzare una nuova istanza della classe <ph id="ph1">&lt;see cref="T:System.ServiceModel.CommunicationObjectFaultedException" /&gt;</ph> utilizzando il messaggio e l'eccezione interna specificati.</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.ServiceModel.CommunicationObjectFaultedException.#ctor(System.String,System.Exception)">
          <source>Creates a new <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> using the specified <ph id="ph2">`message`</ph> and <ph id="ph3">`innerException`</ph>.</source>
          <target state="translated">Consente di creare un nuovo oggetto <ph id="ph1">&lt;xref:System.ServiceModel.CommunicationObjectFaultedException&gt;</ph> utilizzando i parametri <ph id="ph2">`message`</ph> e <ph id="ph3">`innerException`</ph> specificati.</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>